import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('observability shared chrome', () => {
  it('removes legacy white-on-black tokens from the core shared primitives', () => {
    const panelShellSource = readFileSync(resolve(process.cwd(), 'components/observability/panel-shell.tsx'), 'utf8');
    const railShellSource = readFileSync(resolve(process.cwd(), 'components/observability/rail-shell.tsx'), 'utf8');
    const codePaneSource = readFileSync(resolve(process.cwd(), 'components/observability/code-pane.tsx'), 'utf8');
    const detailRowsSource = readFileSync(resolve(process.cwd(), 'components/observability/detail-rows.tsx'), 'utf8');
    const statGridSource = readFileSync(resolve(process.cwd(), 'components/observability/stat-grid.tsx'), 'utf8');
    const waterfallSource = readFileSync(resolve(process.cwd(), 'components/observability/waterfall.tsx'), 'utf8');
    const selectableEvidenceSource = readFileSync(resolve(process.cwd(), 'components/observability/selectable-evidence-list.tsx'), 'utf8');
    const timelineSource = readFileSync(resolve(process.cwd(), 'components/observability/timeline.tsx'), 'utf8');
    const pageHeaderSource = readFileSync(resolve(process.cwd(), 'components/observability/page-header.tsx'), 'utf8');
    const toolbarSource = readFileSync(resolve(process.cwd(), 'components/observability/toolbar.tsx'), 'utf8');
    const tabStripSource = readFileSync(resolve(process.cwd(), 'components/observability/tab-strip.tsx'), 'utf8');
    const searchInputSource = readFileSync(resolve(process.cwd(), 'components/observability/search-input.tsx'), 'utf8');
    const controlButtonSource = readFileSync(resolve(process.cwd(), 'components/observability/control-button.tsx'), 'utf8');
    const echartsPanelSource = readFileSync(resolve(process.cwd(), 'components/observability/echarts-panel.tsx'), 'utf8');
    const statusStateSource = readFileSync(resolve(process.cwd(), 'components/observability/status-state.tsx'), 'utf8');
    const selectableRowsSource = readFileSync(resolve(process.cwd(), 'components/observability/selectable-rows.tsx'), 'utf8');
    const chipToggleSource = readFileSync(resolve(process.cwd(), 'components/observability/chip-toggle.tsx'), 'utf8');
    const signalBarsSource = readFileSync(resolve(process.cwd(), 'components/observability/signal-bars.tsx'), 'utf8');
    const statusBadgeSource = readFileSync(resolve(process.cwd(), 'components/observability/status-badge.tsx'), 'utf8');
    const selectableCardGridSource = readFileSync(resolve(process.cwd(), 'components/observability/selectable-card-grid.tsx'), 'utf8');

    expect(panelShellSource).not.toContain('text-white/92');
    expect(panelShellSource).not.toContain('text-white/42');
    expect(panelShellSource).not.toContain('#f2ede4');
    expect(railShellSource).not.toContain('rounded-[18px]');
    expect(railShellSource).not.toContain('linear-gradient(180deg');
    expect(codePaneSource).not.toContain('border-white/10');
    expect(codePaneSource).not.toContain('text-white/62');
    expect(detailRowsSource).not.toContain('border-white/10');
    expect(detailRowsSource).not.toContain('text-white/78');
    expect(detailRowsSource).not.toContain('#e3ddd3');
    expect(statGridSource).not.toContain('divide-white/10');
    expect(statGridSource).not.toContain('border-white/10');
    expect(statGridSource).not.toContain('#f3eee6');
    expect(statGridSource).not.toContain('bg-white/[0.03]');
    expect(waterfallSource).not.toContain('border-white/7');
    expect(waterfallSource).not.toContain('bg-black/10');
    expect(waterfallSource).not.toContain('text-white/34');
    expect(waterfallSource).not.toContain('text-white/80');
    expect(selectableEvidenceSource).not.toContain('border-white/10');
    expect(selectableEvidenceSource).not.toContain('text-white/65');
    expect(selectableEvidenceSource).not.toContain('text-white/34');
    expect(timelineSource).not.toContain('border-white/8');
    expect(timelineSource).not.toContain('bg-black/10');
    expect(timelineSource).not.toContain('text-white/62');
    expect(pageHeaderSource).not.toContain('text-white/94');
    expect(pageHeaderSource).not.toContain('#f3eee6');
    expect(pageHeaderSource).not.toContain('#8f887d');
    expect(toolbarSource).not.toContain('bg-white/[0.03]');
    expect(toolbarSource).not.toContain('text-white/82');
    expect(toolbarSource).not.toContain('border-white/10');
    expect(tabStripSource).not.toContain('text-white/92');
    expect(tabStripSource).not.toContain('#ece5d9');
    expect(tabStripSource).not.toContain('border-white/10');
    expect(searchInputSource).not.toContain('text-white/88');
    expect(searchInputSource).not.toContain('#ebe4d9');
    expect(searchInputSource).not.toContain('bg-black/10');
    expect(controlButtonSource).not.toContain('bg-white/[0.04]');
    expect(controlButtonSource).not.toContain('text-white/70');
    expect(controlButtonSource).not.toContain('#f3eee6');
    expect(controlButtonSource).not.toContain('#a69d90');
    expect(echartsPanelSource).not.toContain('border-white/10');
    expect(echartsPanelSource).not.toContain('border-white/8');
    expect(echartsPanelSource).not.toContain('linear-gradient(180deg');
    expect(echartsPanelSource).not.toContain('bg-white/6');
    expect(statusStateSource).not.toContain('border-white/10');
    expect(statusStateSource).not.toContain('bg-[hsl(var(--secondary)/0.35)]');
    expect(statusStateSource).not.toContain('text-[hsl(var(--foreground))]');
    expect(statusStateSource).not.toContain('text-[hsl(var(--muted-foreground))]');
    expect(statusStateSource).not.toContain('border-red-500/25');
    expect(selectableRowsSource).not.toContain('border-white/12');
    expect(selectableRowsSource).not.toContain('text-white/78');
    expect(selectableRowsSource).not.toContain('#8f887d');
    expect(chipToggleSource).not.toContain('border-white/12');
    expect(chipToggleSource).not.toContain('#f3eee6');
    expect(chipToggleSource).not.toContain('#a69d90');
    expect(signalBarsSource).not.toContain('text-white/62');
    expect(signalBarsSource).not.toContain('bg-white/[0.06]');
    expect(statusBadgeSource).not.toContain('border-white/10');
    expect(statusBadgeSource).not.toContain('bg-white/[0.03]');
    expect(statusBadgeSource).not.toContain('text-white/62');
    expect(selectableCardGridSource).not.toContain('border-white/10');
    expect(selectableCardGridSource).not.toContain('text-white/92');
    expect(selectableCardGridSource).not.toContain('#f2ede4');
    expect(selectableCardGridSource).not.toContain('#b5ada1');
  });

  it('adopts shared ops tokens across the core shared primitives', () => {
    const panelShellSource = readFileSync(resolve(process.cwd(), 'components/observability/panel-shell.tsx'), 'utf8');
    const railShellSource = readFileSync(resolve(process.cwd(), 'components/observability/rail-shell.tsx'), 'utf8');
    const codePaneSource = readFileSync(resolve(process.cwd(), 'components/observability/code-pane.tsx'), 'utf8');
    const detailRowsSource = readFileSync(resolve(process.cwd(), 'components/observability/detail-rows.tsx'), 'utf8');
    const statGridSource = readFileSync(resolve(process.cwd(), 'components/observability/stat-grid.tsx'), 'utf8');
    const waterfallSource = readFileSync(resolve(process.cwd(), 'components/observability/waterfall.tsx'), 'utf8');
    const selectableEvidenceSource = readFileSync(resolve(process.cwd(), 'components/observability/selectable-evidence-list.tsx'), 'utf8');
    const timelineSource = readFileSync(resolve(process.cwd(), 'components/observability/timeline.tsx'), 'utf8');
    const pageHeaderSource = readFileSync(resolve(process.cwd(), 'components/observability/page-header.tsx'), 'utf8');
    const toolbarSource = readFileSync(resolve(process.cwd(), 'components/observability/toolbar.tsx'), 'utf8');
    const tabStripSource = readFileSync(resolve(process.cwd(), 'components/observability/tab-strip.tsx'), 'utf8');
    const searchInputSource = readFileSync(resolve(process.cwd(), 'components/observability/search-input.tsx'), 'utf8');
    const controlButtonSource = readFileSync(resolve(process.cwd(), 'components/observability/control-button.tsx'), 'utf8');
    const echartsPanelSource = readFileSync(resolve(process.cwd(), 'components/observability/echarts-panel.tsx'), 'utf8');
    const statusStateSource = readFileSync(resolve(process.cwd(), 'components/observability/status-state.tsx'), 'utf8');
    const selectableRowsSource = readFileSync(resolve(process.cwd(), 'components/observability/selectable-rows.tsx'), 'utf8');
    const chipToggleSource = readFileSync(resolve(process.cwd(), 'components/observability/chip-toggle.tsx'), 'utf8');
    const signalBarsSource = readFileSync(resolve(process.cwd(), 'components/observability/signal-bars.tsx'), 'utf8');
    const statusBadgeSource = readFileSync(resolve(process.cwd(), 'components/observability/status-badge.tsx'), 'utf8');
    const selectableCardGridSource = readFileSync(resolve(process.cwd(), 'components/observability/selectable-card-grid.tsx'), 'utf8');

    expect(panelShellSource).toContain('border-[var(--ops-border-color)]');
    expect(panelShellSource).toContain('text-[var(--ops-text-primary)]');
    expect(railShellSource).toContain('bg-[var(--ops-surface-elevated)]');
    expect(railShellSource).toContain('text-[var(--ops-text-tertiary)]');
    expect(codePaneSource).toContain('bg-[var(--ops-surface-raised)]');
    expect(codePaneSource).toContain('text-[var(--ops-text-secondary)]');
    expect(detailRowsSource).toContain('border-[var(--ops-border-color)]');
    expect(detailRowsSource).toContain('text-[var(--ops-text-secondary)]');
    expect(statGridSource).toContain('border-[var(--ops-border-color)]');
    expect(statGridSource).toContain('text-[var(--ops-text-primary)]');
    expect(waterfallSource).toContain('border-[var(--ops-border-color)]');
    expect(waterfallSource).toContain('bg-[var(--ops-surface-panel)]');
    expect(waterfallSource).toContain('text-[var(--ops-text-secondary)]');
    expect(selectableEvidenceSource).toContain('border-[var(--ops-border-color)]');
    expect(selectableEvidenceSource).toContain('text-[var(--ops-text-primary)]');
    expect(timelineSource).toContain('border-[var(--ops-border-color)]');
    expect(timelineSource).toContain('bg-[var(--ops-surface-raised)]');
    expect(pageHeaderSource).toContain('border-[var(--ops-border-color)]');
    expect(pageHeaderSource).toContain('text-[var(--ops-text-primary)]');
    expect(toolbarSource).toContain('bg-[var(--ops-surface-panel)]');
    expect(toolbarSource).toContain('bg-[var(--ops-surface-raised)]');
    expect(tabStripSource).toContain('border-[var(--ops-border-color)]');
    expect(tabStripSource).toContain('text-[var(--ops-text-secondary)]');
    expect(searchInputSource).toContain('text-[var(--ops-text-primary)]');
    expect(searchInputSource).toContain('placeholder:text-[var(--ops-text-tertiary)]');
    expect(controlButtonSource).toContain('border-[var(--ops-border-color)]');
    expect(controlButtonSource).toContain('border-[var(--ops-primary)]');
    expect(controlButtonSource).toContain('text-[var(--ops-text-primary)]');
    expect(controlButtonSource).toContain('text-[var(--ops-text-secondary)]');
    expect(echartsPanelSource).toContain('border-[var(--ops-border-color)]');
    expect(echartsPanelSource).toContain('bg-[var(--ops-surface-panel)]');
    expect(echartsPanelSource).toContain('bg-[var(--ops-border-color)]');
    expect(statusStateSource).toContain('border-[var(--ops-border-color)]');
    expect(statusStateSource).toContain('bg-[var(--ops-surface-panel)]');
    expect(statusStateSource).toContain('text-[var(--ops-text-primary)]');
    expect(statusStateSource).toContain('text-[var(--ops-text-secondary)]');
    expect(statusStateSource).toContain('border-[rgba(216,111,91,0.28)]');
    expect(selectableRowsSource).toContain('border-[var(--ops-border-color)]');
    expect(selectableRowsSource).toContain('border-[var(--ops-primary)]');
    expect(selectableRowsSource).toContain('text-[var(--ops-text-primary)]');
    expect(selectableRowsSource).toContain('text-[var(--ops-text-secondary)]');
    expect(chipToggleSource).toContain('border-[var(--ops-border-color)]');
    expect(chipToggleSource).toContain('border-[var(--ops-primary)]');
    expect(chipToggleSource).toContain('text-[var(--ops-text-primary)]');
    expect(signalBarsSource).toContain('text-[var(--ops-text-secondary)]');
    expect(signalBarsSource).toContain('bg-[var(--ops-surface-raised)]');
    expect(signalBarsSource).toContain('bg-[var(--ops-primary)]');
    expect(statusBadgeSource).toContain('border-[var(--ops-border-color)]');
    expect(statusBadgeSource).toContain('bg-[var(--ops-surface-raised)]');
    expect(statusBadgeSource).toContain('text-[var(--ops-text-secondary)]');
    expect(selectableCardGridSource).toContain('border-[var(--ops-border-color)]');
    expect(selectableCardGridSource).toContain('border-[var(--ops-primary)]');
    expect(selectableCardGridSource).toContain('bg-[var(--ops-surface-raised)]');
    expect(selectableCardGridSource).toContain('text-[var(--ops-text-primary)]');
  });
});
