tasks:

    - name: Run backend
      before: cd manager
      command: |
          gp sync-await setup-backend
          mvn spring-boot:run

    - name: Run frontend
      before: cd web-app
      command: |
          gp sync-await setup-frontend
          yarn start --public-host "`gp url 4200`"
      openMode: split-right

    - name: Setup backend
      init: |
          sdk install java 17.0.11.fx-zulu < /dev/null
          sdk default java 17.0.11.fx-zulu < /dev/null
          mvn clean install -DskipTests
      command: |
          gp sync-done setup-backend
          exit 0

    - name: Setup frontend
      init: |
          cd web-app && yarn install
      command: |
          gp sync-done setup-frontend
          exit 0
      openMode: split-right

vscode:
    extensions:
        - vscjava.vscode-java-pack
        - editorconfig.editorconfig
        - dbaeumer.vscode-eslint
        - stylelint.vscode-stylelint
        - DavidAnson.vscode-markdownlint
        - ms-azuretools.vscode-docker
        - cweijan.vscode-database-client2
        - GitHub.vscode-pull-request-github

ports:
    - port: 4200
      name: Hertzbeat
      onOpen: open-browser

    - port: 1157
      onOpen: ignore

    - port: 1158
      onOpen: ignore
