#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths-ignore:
    - '**/*.md'
    - '**/*.json'
    - '**/*.iml'
    - '**/*.ini'
    - '**/*.svg'
    - '**/*.png'
    - '**/*.MD'
    - '**/*.ftl'
    - '**/*.tpl'
    - '**/*.pl'
    - '**/*.dict'
    - '**/*.awk'
    - "**/*.lock"
    - '**/*.crt'
    - '**/*.pem'
    - '**/*.js'
    - '**/*.less'
    - '**/*.txt'
    - '**/target/**'
    - '.gitattributes'
    - '.gitpod.yml'
    - '**/.gitignore'
    - '**/.gitkeep'
    - 'home/**'
    - 'material/**'
    - 'LICENSE'
    - 'NOTICE'
    - 'DISCLAIMER'
    - '**/LICENSE'
    - '**/NOTICE'
    - '.all-contributorsrc'
    - '**/*.AbstractCollect'
    - '**/*.MockMaker'
    - '.prettierrc'
    - '.browserslistrc'
    - '.editorconfig'
    - '.eslintignore'
    - '.eslintrc.js'
    - '.stylelintrc'
    - '.prettierignore'
    - '.prettierrc.js'
    - 'karma.conf.js'
    - 'proxy.conf.js'
    - '.helmignore'
    - 'web-app/src/app/core/**'
    - 'web-app/src/app/layout/**'
    - 'web-app/src/app/routes/routes.module.ts'
    - 'web-app/src/app/routes/routes-routing.module.ts'
    - 'web-app/src/app/shared/json-schema/**'
    - 'web-app/src/app/shared/index.ts'
    - 'web-app/src/app/shared/shared.module.ts'
    - 'web-app/src/app/shared/shared-delon.module.ts'
    - 'web-app/src/app/shared/shared-zorro.module.ts'
    - 'web-app/src/app/app.module.ts'
    - 'web-app/src/app/app.component.ts'
    - 'web-app/src/app/global-config.module.ts'
    - 'web-app/src/app/icons-provider.module.ts'
    - 'web-app/src/assets/color.less'
    - 'web-app/src/assets/style.compact.less'
    - 'web-app/src/assets/style.dark.less'
    - 'web-app/src/environments/**'
    - 'web-app/src/styles/**'
    - 'web-app/src/index.html'
    - 'web-app/src/main.ts'
    - 'web-app/src/polyfills.ts'
    - 'web-app/src/style-icons.ts'
    - 'web-app/src/style-icons-auto.ts'
    - 'web-app/src/style.less'
    - 'web-app/src/test.ts'
    - 'web-app/src/typings.d.ts'
    
  comment: on-failure

dependency:
  files:
    - pom.xml
    - web-app/package.json
    

