import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('compatibility entrypoint posture', () => {
  it('keeps compatibility routes on their shared owners', () => {
    const dashboardSource = readFileSync(resolve(process.cwd(), 'app/dashboard/page.tsx'), 'utf8');
    const alertsSource = readFileSync(resolve(process.cwd(), 'app/alerts/page.tsx'), 'utf8');
    const alertCenterSource = readFileSync(resolve(process.cwd(), 'app/alert/center/page.tsx'), 'utf8');
    const eventsSource = readFileSync(resolve(process.cwd(), 'app/events/page.tsx'), 'utf8');
    const loginSource = readFileSync(resolve(process.cwd(), 'app/login/page.tsx'), 'utf8');
    const statusPublicSource = readFileSync(resolve(process.cwd(), 'app/status/public/page.tsx'), 'utf8');
    const settingSource = readFileSync(resolve(process.cwd(), 'app/setting/page.tsx'), 'utf8');
    const settingSettingsSource = readFileSync(resolve(process.cwd(), 'app/setting/settings/page.tsx'), 'utf8');
    const logStreamSource = readFileSync(resolve(process.cwd(), 'app/log/stream/page.tsx'), 'utf8');
    const logIntegrationSource = readFileSync(resolve(process.cwd(), 'app/log/integration/page.tsx'), 'utf8');
    const logIntegrationSourceAlias = readFileSync(resolve(process.cwd(), 'app/log/integration/[source]/page.tsx'), 'utf8');

    expect(dashboardSource).toContain('buildDashboardCompatRouteUrl');
    expect(dashboardSource).toContain('redirect(');
    expect(dashboardSource).not.toContain("from '../overview/page'");
    expect(alertsSource).toContain('buildAlertCompatRouteUrlFromSearchParams');
    expect(alertsSource).not.toContain('createCompatSearchParamReader');
    expect(alertsSource).toContain('redirect(');
    expect(alertCenterSource).toContain('buildAlertCompatRouteUrlFromSearchParams');
    expect(alertCenterSource).not.toContain("from '../../../lib/compat/search-params'");
    expect(eventsSource).toContain('buildLogCompatRouteUrlFromSearchParams');
    expect(eventsSource).not.toContain('createCompatSearchParamReader');
    expect(eventsSource).toContain("view: 'list'");
    expect(eventsSource).toContain('redirect(');
    expect(loginSource).toContain('buildLoginCompatRouteUrl');
    expect(loginSource).not.toContain("from '../../lib/compat/search-params'");
    expect(statusPublicSource).toContain('buildPublicStatusCompatRouteUrl');
    expect(statusPublicSource).not.toContain("from '../../../lib/compat/search-params'");
    expect(settingSource).toContain('buildSettingsCompatRouteUrl');
    expect(settingSource).not.toContain("from '../../lib/compat/search-params'");
    expect(settingSettingsSource).toContain('buildSettingsCompatRouteUrl');
    expect(settingSettingsSource).not.toContain("from '../../../lib/compat/search-params'");
    expect(alertsSource).not.toContain('function createSearchParamReader');
    expect(alertsSource).not.toContain("from '../alert/page'");
    expect(eventsSource).not.toContain('function createSearchParamReader');
    expect(eventsSource).not.toContain("from '../log/manage/log-manage-page'");
    expect(eventsSource).not.toContain('forcedView="explorer"');
    expect(loginSource).not.toContain('function buildSearchParams');
    expect(alertCenterSource).not.toContain("redirect('/alert')");
    expect(statusPublicSource).not.toContain("redirect('/status')");
    expect(settingSource).not.toContain("redirect('/setting/settings')");
    expect(settingSettingsSource).not.toContain("redirect('/setting/settings/config')");
    expect(logStreamSource).toContain('data-log-stream-canonical-live-route="log-manage-stream"');
    expect(logStreamSource).toContain('forcedView="stream"');
    expect(logStreamSource).toContain('showViewToggle={false}');
    expect(logStreamSource).not.toContain('data-log-stream-surface="angular-log-stream"');
    expect(logStreamSource).not.toContain('data-log-stream-toolbar="angular-actions"');
    expect(logStreamSource).not.toContain('buildLogCompatRouteUrl');
    expect(logStreamSource).not.toContain('redirect(');
    expect(logStreamSource).toContain('LogManagePage');
    expect(logIntegrationSource).toContain('buildLogIntegrationIngestionHref');
    expect(logIntegrationSource).toContain('createSearchParamReader');
    expect(logIntegrationSource).toContain('redirect(');
    expect(logIntegrationSource).not.toContain('LogIntegrationRedirectShell');
    expect(logIntegrationSourceAlias).toContain('buildLogIntegrationIngestionHref');
    expect(logIntegrationSourceAlias).toContain('createSearchParamReader(resolvedSearchParams)');
    expect(logIntegrationSourceAlias).not.toContain('resolved.source');
    expect(logIntegrationSourceAlias).toContain('redirect(');
  });
});
