package org.apache.hertzbeat.manager.pojo.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ZhiPuAIResponse {

    /**
     * Task order number generated by the AI open platform. Use this order number when invoking the request result interface
     */
    private String id;

    /**
     * The request creation time is a Unix timestamp in seconds
     */
    private Long created;

    /**
     * response message
     */
    private List<Choice> choices;

    /**
     * Returns the number of tokens invoked by the model at the end.
     */
    private Tokens usage;

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public class Choice {
        private int index;
        private AIMessage delta;
    }

    @Data
    @AllArgsConstructor
    @NoArgsConstructor
    public class Tokens {

        /**
         * The number of tokens entered by users
         */
        @JsonProperty("prompt_tokens")
        private Integer promptTokens;

        /**
         * The number of tokens that the model outputs
         */
        @JsonProperty("completion_tokens")
        private Integer completionTokens;

        /**
         * Total number of tokens
         */
        @JsonProperty("total_tokens")
        private Integer totalTokens;
    }

}

