# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

patchedDependencies:
  '@perses-dev/logs-table-plugin@0.3.0': patches/@perses-dev__logs-table-plugin@0.3.0.patch
  '@perses-dev/trace-table-plugin@0.11.0': patches/@perses-dev__trace-table-plugin@0.11.0.patch
  '@perses-dev/tracing-gantt-chart-plugin@0.13.0': patches/@perses-dev__tracing-gantt-chart-plugin@0.13.0.patch
  '@perses-dev/components@0.54.0': patches/@perses-dev__components@0.54.0.patch
  '@perses-dev/timeseries-chart-plugin@0.13.0': patches/@perses-dev__timeseries-chart-plugin@0.13.0.patch
  '@perses-dev/plugin-system@0.54.0': patches/@perses-dev__plugin-system@0.54.0.patch
