/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hertzbeat.manager.setup.identity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

class IdentityMigrationResourceTest {
    private static final String MIGRATION = "V205__add_identity_and_installation.sql";
    private static final List<String> REQUIRED_SCHEMA = List.of(
            "username VARCHAR(64) NOT NULL",
            "password_hash VARCHAR(100) NOT NULL",
            "roles VARCHAR(128) NOT NULL",
            "credential_version BIGINT NOT NULL",
            "disabled BOOLEAN NOT NULL",
            "bootstrap_slot SMALLINT",
            "uk_hzb_account_username UNIQUE (username)",
            "uk_hzb_account_bootstrap UNIQUE (bootstrap_slot)",
            "installation_fingerprint VARCHAR(64) NOT NULL UNIQUE",
            "complete BOOLEAN NOT NULL");

    @Test
    void h2MigrationExecutesAndEnforcesOneBootstrapAdministrator() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:identity-migration;DB_CLOSE_DELAY=-1");
        try (Connection connection = dataSource.getConnection()) {
            executeMigration(connection, migration("h2"));
            try (Statement statement = connection.createStatement()) {
                statement.executeUpdate(accountInsert("owner", 1));
                SQLException conflict = assertThrows(SQLException.class,
                        () -> statement.executeUpdate(accountInsert("other", 1)));
                assertEquals("23505", conflict.getSQLState());
                statement.executeUpdate("INSERT INTO hzb_installation "
                        + "(id, installation_fingerprint, complete) VALUES (1, '" + "a".repeat(64) + "', TRUE)");
            }
        }
    }

    @Test
    void allDatabaseMigrationsDeclareTheSameIdentityBoundary() throws Exception {
        for (String database : List.of("h2", "mysql", "postgresql")) {
            String migration = migration(database);
            for (String required : REQUIRED_SCHEMA) {
                assertTrue(migration.contains(required), () -> database + " migration is missing: " + required);
            }
        }
        assertTrue(migration("mysql").contains("AUTO_INCREMENT"));
        assertTrue(migration("h2").contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(migration("postgresql").contains("GENERATED BY DEFAULT AS IDENTITY"));
    }

    private static String accountInsert(String username, int bootstrapSlot) {
        return "INSERT INTO hzb_account "
                + "(username, password_hash, roles, credential_version, disabled, bootstrap_slot) VALUES ('"
                + username + "', 'hash', 'admin', 1, FALSE, " + bootstrapSlot + ")";
    }

    static void executeMigration(Connection connection, String migration) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            for (String sql : migration.replaceAll("(?m)^--.*$", "").split(";")) {
                if (!sql.isBlank()) {
                    statement.execute(sql);
                }
            }
        }
    }

    static String migration(String database) throws IOException {
        String resource = "/db/migration/" + database + "/" + MIGRATION;
        try (InputStream stream = IdentityMigrationResourceTest.class.getResourceAsStream(resource)) {
            if (stream == null) {
                throw new IOException("Migration resource is missing: " + resource);
            }
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        }
    }
}
