import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('dashboard source edit browser smoke coverage', () => {
  it('keeps the dashboard to source edit to dashboard return loop covered by the Playwright smoke', () => {
    const source = readFileSync(resolve(process.cwd(), 'scripts/dashboard-source-edit-browser-smoke.spec.ts'), 'utf8');

    expect(source).toContain('data-dashboard-composition-preview-action="edit-source"');
    expect(source).toContain('data-log-manage-dashboard-panel-draft-action="update-current"');
    expect(source).toContain('data-trace-manage-dashboard-panel-draft-action="update-current"');
    expect(source).toContain('data-otlp-metrics-dashboard-panel-draft-action="update-current"');
    expect(source).toContain("path === '/api/signal/dashboard' && method === 'PUT'");
    expect(source).toContain('savedDashboardRoutes');
    expect(source).toContain('data-log-manage-dashboard-panel-draft-return-action="dashboard"');
    expect(source).toContain('data-trace-manage-dashboard-panel-draft-return-action="dashboard"');
    expect(source).toContain('data-otlp-metrics-dashboard-panel-draft-return-action="dashboard"');
    expect(source).toContain('data-dashboard-composition-preview-edit-source');
    expect(source).toContain('data-dashboard-composition-preview-edit-source-dashboard');
    expect(source).toContain('data-dashboard-composition-preview-edit-source-panel');
    expect(source).toContain('data-dashboard-composition-preview-edit-source-draft');
    expect(source).toContain('search=latency');
    expect(source).toContain('operationName=GET+%2Fbilling');
    expect(source).toContain('process.runtime.jvm.memory.used');
    expect(source).toContain('applies dashboard variable URL overrides to preview routes and runtime execution');
    expect(source).toContain('var-service.name=billing');
    expect(source).toContain('data-dashboard-composition-filter-variable="service.name"');
    expect(source).toContain('data-dashboard-composition-preview-raw-route');
    expect(source).toContain('data-dashboard-composition-preview-route');
    expect(source).toContain('data-dashboard-composition-preview-edit-href');
    expect(source).toContain('var-service\\.name%3Dbilling');
    expect(source).toContain('data-dashboard-composition-time-range-input="preset"');
    expect(source).toContain('timeRange=last-30m');
    expect(source).toContain('var-service\\.name=billing');
    expect(source).toContain('data-dashboard-composition-filter-option="checkout"');
    expect(source).toContain('var-service\\.name=checkout');
    expect(source).toContain('serviceName=checkout');
    expect(source).toContain('data-dashboard-composition-filter-variable-action="add-panel-draft"');
    expect(source).toContain('data-dashboard-composition-filter-variable-action-templates');
    expect(source).toContain('data-dashboard-composition-filter-variable-action-compose');
    expect(source).toContain("title: 'Filter panel: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel table: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel latency p95: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel request rate: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel error rate: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel apdex: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel db calls rate: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel db call duration: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel external calls rate: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel external call duration: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel key operations: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel logs: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel log errors: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel traces: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel trace errors: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel exceptions: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel exception messages: service.name=checkout'");
    expect(source).toContain("title: 'Filter panel firing alerts: service.name=checkout'");
    expect(source).toContain('severityText=ERROR');
    expect(source).toContain('errorOnly=true');
    expect(source).toContain('/api/alerts/group');
    expect(source).toContain('/api/alerts/summary');
    expect(source).toContain('priorityCriticalNum');
    expect(source).toContain("signal: 'alerts'");
    expect(source).toContain("status: 'firing'");
    expect(source).toContain('status_code%3D%22STATUS_CODE_ERROR%22');
    expect(source).toContain('template=service-apdex');
    expect(source).toContain('template=service-db-call-duration');
    expect(source).toContain('template=service-external-call-duration');
    expect(source).toContain('template=service-exceptions');
    expect(source).toContain('template=service-exception-messages');
    expect(source).toContain('query=signoz_db_latency_count');
    expect(source).toContain('query=signoz_external_call_latency_count');
    expect(source).toContain('query=http.server.duration.bucket');
    expect(source).toContain('groupBy=operation');
    expect(source).toContain("source: 'signal-dashboard-filter-selection'");
    expect(source).toContain("templateKey: 'metrics-graph'");
    expect(source).toContain("templateKey: 'metrics-table'");
    expect(source).toContain("templateKey: 'metrics-latency-p95'");
    expect(source).toContain("templateKey: 'metrics-request-rate'");
    expect(source).toContain("templateKey: 'metrics-error-rate'");
    expect(source).toContain("templateKey: 'metrics-apdex'");
    expect(source).toContain("templateKey: 'metrics-db-call-rate'");
    expect(source).toContain("templateKey: 'metrics-db-call-duration'");
    expect(source).toContain("templateKey: 'metrics-external-call-rate'");
    expect(source).toContain("templateKey: 'metrics-external-call-duration'");
    expect(source).toContain("templateKey: 'metrics-key-operations'");
    expect(source).toContain("templateKey: 'logs-list'");
    expect(source).toContain("templateKey: 'logs-errors'");
    expect(source).toContain("templateKey: 'traces-table'");
    expect(source).toContain("templateKey: 'traces-errors'");
    expect(source).toContain("templateKey: 'traces-exceptions'");
    expect(source).toContain("templateKey: 'traces-exception-messages'");
    expect(source).toContain("templateKey: 'alerts-firing'");
    expect(source).toContain('savedDashboards');
    expect(source).toContain("path === '/api/signal/dashboard' && method === 'PUT'");
    expect(source).toContain("'Service latency'");
    expect(source).toContain('data-dashboard-runtime-metrics-chart-point-timestamp="1713200000000"');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-source="metrics-point"');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-related-handoff');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-action="open-related"');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-breakout-attributes');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-action="breakout-panel-draft"');
    expect(source).toContain("source: 'signal-dashboard-runtime-breakout'");
    expect(source).toContain("title: 'Breakout panel: service.name'");
    expect(source).toContain('groupBy=service.name');
    expect(source).toContain('creates logs and traces breakout drafts from synchronized dashboard evidence');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-signal="logs"');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-signal="traces"');
    expect(source).toContain("title: 'Breakout panel: resource:service.name'");
    expect(source).toContain('groupBy=resource%3Aservice.name');
    expect(source).toContain("sourcePanelId: 'runtime-logs'");
    expect(source).toContain("sourcePanelId: 'runtime-traces'");
    expect(source).toContain('[data-dashboard-runtime-object-panel="runtime-log-group"]');
    expect(source).toContain('[data-dashboard-runtime-object-panel="runtime-trace-group"]');
    expect(source).toContain('resourceFilter=service.version%3D1.2.3');
    expect(source).toContain('data-dashboard-composition-runtime-preview-row-related-signal');
    expect(source).toContain('data-dashboard-composition-runtime-preview-row-related-handoff');
    expect(source).toContain('data-dashboard-composition-runtime-preview-row-action="open-related"');
    expect(source).toContain('saves a service overview dashboard from URL service and entity context');
    expect(source).toContain('installDashboardServiceOverviewMocks');
    expect(source).toContain('data-dashboard-service-overview-action="save"');
    expect(source).toContain('data-dashboard-service-overview-context="ready"');
    expect(source).toContain('service-checkout-overview');
    expect(source).toContain('Checkout API service overview');
    expect(source).toContain('Service overview request rate: service.name=checkout');
    expect(source).toContain('Service overview error rate: service.name=checkout');
    expect(source).toContain('Service overview apdex: service.name=checkout');
    expect(source).toContain('Service overview log errors: service.name=checkout');
    expect(source).toContain('Service overview exceptions: service.name=checkout');
    expect(source).toContain('Service overview firing alerts: service.name=checkout');
    expect(source).toContain('hertzbeat.entity_type');
    expect(source).toContain('entityType=service');
    expect(source).toContain('data-dashboard-composition-runtime-sync-tooltip-row-action="add-panel-draft"');
    expect(source).toContain('spanScope=all');
    expect(source).toContain('runtimeEvidenceDrafts');
    expect(source).toContain("source: 'signal-dashboard-runtime-evidence'");
    expect(source).toContain("title: 'Evidence panel: http.server.duration'");
    expect(source).toContain("path === '/api/ingestion/otlp/metrics/console'");
    expect(source).toContain('executedMetricServices');
    expect(source).toContain('promotes a saved query view into a reusable dashboard panel draft');
    expect(source).toContain('installDashboardSavedViewPromotionMocks');
    expect(source).toContain('data-dashboard-saved-view-row="metrics-checkout-p95"');
    expect(source).toContain('data-dashboard-saved-view-label-input="metrics-checkout-p95"');
    expect(source).toContain('data-dashboard-saved-view-description-input="metrics-checkout-p95"');
    expect(source).toContain('data-dashboard-saved-view-action="update"');
    expect(source).toContain('data-dashboard-saved-view-action="add-panel"');
    expect(source).toContain('data-dashboard-saved-view-action="delete"');
    expect(source).toContain('data-dashboard-panel-draft-action="duplicate"');
    expect(source).toContain("path === '/api/signal/saved-view' && method === 'PUT'");
    expect(source).toContain("path === '/api/signal/dashboard-panel-draft' && method === 'PUT'");
    expect(source).toContain('promotedDrafts');
    expect(source).toContain('updatedSavedViews');
    expect(source).toContain("label: 'Checkout p99'");
    expect(source).toContain("title: 'Checkout p99 Copy'");
    expect(source).toContain("source: 'signal-dashboard-panel-duplicate'");
    expect(source).toContain("duplicatedFromSource: 'signal-saved-view'");
    expect(source).toContain('savedViewRouteSummaryText');
    expect(source).toContain('data-dashboard-panel-draft-source-summary');
    expect(source).toContain('query=http.server.duration, serviceName=checkout, inspector=graph');
    expect(source).toContain('deletedSavedViews');
    expect(source).toContain("toContain('metrics:metrics-checkout-p95')");
    expect(source).toContain('data-dashboard-panel-draft-row');
    expect(source).not.toContain('returnLabel=');
  });
});
