import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('live dashboard source edit browser smoke contract', () => {
  it('keeps the live smoke on real login, real signal dashboard APIs, persistence verification, and cleanup', () => {
    const source = readFileSync(resolve(process.cwd(), 'scripts/dashboard-source-edit-live-browser-smoke.spec.ts'), 'utf8');

    expect(source).toContain("DASHBOARD_SOURCE_EDIT_LIVE_BROWSER_BASE_URL");
    expect(source).toContain("'/api/account/auth/form'");
    expect(source).toContain("tokenBoundary: 'bff-cookie'");
    expect(source).not.toContain("window.localStorage.setItem('Authorization'");
    expect(source).not.toContain("window.localStorage.setItem('refresh-token'");
    expect(source).toContain("'/api/signal/dashboard-panel-draft'");
    expect(source).toContain("'/api/signal/dashboard'");
    expect(source).toContain("'/api/signal/saved-view'");
    expect(source).toContain("api.delete(`${baseUrl}/api/signal/saved-view/metrics/");
    expect(source).toContain("requestJson<SignalSavedView[]>(api, 'GET', `/api/signal/saved-view/${signal}`)");
    expect(source).toContain("requestJson<SignalDashboard[]>(api, 'GET', '/api/signal/dashboard')");
    expect(source).toContain("requestJson<SignalDashboardPanelDraft[]>(api, 'GET', `/api/signal/dashboard-panel-draft/${signal}`)");
    expect(source).toContain("api.delete(`${baseUrl}/api/signal/dashboard/");
    expect(source).toContain("api.delete(\n    `${baseUrl}/api/signal/dashboard-panel-draft/");
    expect(source).toContain("expect(widget?.route).toContain(signalCase.editedNeedle)");
    expect(source).toContain("expect(payload.dashboardPanelEdit).toEqual(expect.objectContaining({");
    expect(source).toContain("promotes a saved query view through real saved-view and panel-draft APIs");
    expect(source).toContain("promotes logs, traces, and metrics saved views into a persisted replay dashboard");
    expect(source).toContain("saves a service overview dashboard from URL service and entity context");
    expect(source).toContain("buildSignalServiceOverviewDashboard");
    expect(source).toContain("data-dashboard-service-overview-action=\"save\"");
    expect(source).toContain("data-dashboard-service-overview-context=\"ready\"");
    expect(source).toContain("Checkout API service overview");
    expect(source).toContain("expect(persistedWidgets.map(widget => widget.title)).toEqual(expect.arrayContaining([");
    expect(source).toContain("'Service overview request rate: service.name=checkout'");
    expect(source).toContain("'Service overview error rate: service.name=checkout'");
    expect(source).toContain("'Service overview apdex: service.name=checkout'");
    expect(source).toContain("'Service overview log errors: service.name=checkout'");
    expect(source).toContain("'Service overview exceptions: service.name=checkout'");
    expect(source).toContain("'Service overview firing alerts: service.name=checkout'");
    expect(source).toContain("expect.objectContaining({ name: 'hertzbeat.entity_id', type: 'dynamic', value: '4200' })");
    expect(source).toContain("expect.objectContaining({ name: 'hertzbeat.entity_type', type: 'dynamic', value: 'service' })");
    expect(source).toContain("buildSignalDashboardExecutionPlans(persistedDashboard)");
    expect(source).toContain("expect(plans.map(plan => plan.signal)).toEqual(expect.arrayContaining(['metrics', 'logs', 'traces', 'alerts']))");
    expect(source).toContain("entityType=service");
    expect(source).toContain("template=service-apdex");
    expect(source).toContain("/logs/list");
    expect(source).toContain("/traces/stats/group-by");
    expect(source).toContain("/alerts/group");
    expect(source).toContain("buildThreeSignalWorkbenchDashboardReplayExpectations");
    expect(source).toContain("buildThreeSignalWorkbenchExpectedDashboardVariables");
    expect(source).toContain("seedReplaySavedView(page.context().request, expectation, proofKey)");
    expect(source).toContain("source: 'dashboard-saved-view-replay-live-smoke'");
    expect(source).toContain("data-dashboard-saved-view-row");
    expect(source).toContain("data-dashboard-saved-view-action=\"add-panel\"");
    expect(source).toContain("buildSignalDashboardCompositionFromDrafts");
    expect(source).toContain("title: 'Live saved-view replay dashboard'");
    expect(source).toContain("buildSignalDashboardExecutionPlans(persistedDashboard)");
    expect(source).toContain("savedViewRouteSummary: expect.objectContaining(item.panelDraft.expectedRouteSummary)");
    expect(source).toContain("const persistedVariables = parseVariables(persistedDashboard)");
    expect(source).toContain("buildThreeSignalWorkbenchExpectedDashboardVariables().map(variable => expect.objectContaining(variable))");
    expect(source).toContain("assertPlanMatchesReplayExpectation");
    expect(source).toContain("expect(primaryUrl.pathname).toBe(expectation.replay.primaryPath)");
    expect(source).toContain("expect(primaryUrl.searchParams.get(key), `${expectation.signal} replay query ${key}`).toBe(String(value))");
    expect(source).toContain("expect(primaryUrl.searchParams.get(key), `${expectation.signal} replay should not include ${key}`).toBeNull()");
    expect(source).toContain("expect(persistedWidgets.map(widget => widget.signal)).toEqual(['logs', 'traces', 'metrics'])");
    expect(source).toContain("data-dashboard-composition-preview-route");
    expect(source).toContain("liveProof=${proofKey}");
    expect(source).toContain("cleanupSavedViewReplay");
    expect(source).toContain("api.delete(`${baseUrl}/api/signal/saved-view/${encodeURIComponent(item.signal)}/${encodeURIComponent(item.seededViewKey)}`");
    expect(source).toContain("seedSavedView(page.context().request, viewKey)");
    expect(source).toContain('data-dashboard-saved-view-label-input');
    expect(source).toContain('data-dashboard-saved-view-description-input');
    expect(source).toContain('data-dashboard-saved-view-action="update"');
    expect(source).toContain('data-dashboard-saved-view-action="add-panel"');
    expect(source).toContain('data-dashboard-saved-view-action="delete"');
    expect(source).toContain('data-dashboard-panel-draft-action="duplicate"');
    expect(source).toContain("label: 'Live checkout p99'");
    expect(source).toContain("description: 'Live saved view update smoke'");
    expect(source).toContain("source: 'signal-saved-view'");
    expect(source).toContain("savedViewId: viewKey");
    expect(source).toContain("title: 'Live checkout p99 Copy'");
    expect(source).toContain("source: 'signal-dashboard-panel-duplicate'");
    expect(source).toContain("duplicatedFromSource: 'signal-saved-view'");
    expect(source).toContain("[promotedDraftKey, duplicatedDraftKey].filter");
    expect(source).toContain('savedViewRouteSummaryText');
    expect(source).toContain('data-dashboard-panel-draft-source-summary');
    expect(source).toContain('query=http.server.duration, serviceName=checkout, inspector=graph, timeRange=last-1h');
    expect(source).toContain("views.some(view => view.viewKey === viewKey)");
    expect(source).toContain("data-dashboard-panel-draft-row");
    expect(source).toContain("applies dashboard variable URL overrides through real dashboard APIs");
    expect(source).toContain("buildVariableDashboard(dashboardKey)");
    expect(source).toContain('var-service.name=billing');
    expect(source).toContain('data-dashboard-composition-filter-variable="service.name"');
    expect(source).toContain('data-dashboard-composition-preview-raw-route');
    expect(source).toContain('data-dashboard-composition-preview-route');
    expect(source).toContain('data-dashboard-composition-preview-edit-href');
    expect(source).toContain('var-service\\.name%3Dbilling');
    expect(source).toContain('data-dashboard-composition-filter-variable-action="add-panel-draft"');
    expect(source).toContain("title === 'Filter panel: service.name=billing'");
    expect(source).toContain("title === 'Filter panel table: service.name=billing'");
    expect(source).toContain("title === 'Filter panel latency p95: service.name=billing'");
    expect(source).toContain("title === 'Filter panel request rate: service.name=billing'");
    expect(source).toContain("title === 'Filter panel error rate: service.name=billing'");
    expect(source).toContain("title === 'Filter panel apdex: service.name=billing'");
    expect(source).toContain("title === 'Filter panel db calls rate: service.name=billing'");
    expect(source).toContain("title === 'Filter panel db call duration: service.name=billing'");
    expect(source).toContain("title === 'Filter panel external calls rate: service.name=billing'");
    expect(source).toContain("title === 'Filter panel external call duration: service.name=billing'");
    expect(source).toContain("title === 'Filter panel key operations: service.name=billing'");
    expect(source).toContain("title === 'Filter panel logs: service.name=billing'");
    expect(source).toContain("title === 'Filter panel log errors: service.name=billing'");
    expect(source).toContain("title === 'Filter panel traces: service.name=billing'");
    expect(source).toContain("title === 'Filter panel trace errors: service.name=billing'");
    expect(source).toContain("title === 'Filter panel exceptions: service.name=billing'");
    expect(source).toContain("title === 'Filter panel exception messages: service.name=billing'");
    expect(source).toContain("title === 'Filter panel firing alerts: service.name=billing'");
    expect(source).toContain('severityText=ERROR');
    expect(source).toContain('errorOnly=true');
    expect(source).toContain("loadPanelDrafts(page.context().request, 'alerts')");
    expect(source).toContain("signal: 'alerts'");
    expect(source).toContain('status=firing');
    expect(source).toContain('status_code%3D%22STATUS_CODE_ERROR%22');
    expect(source).toContain('groupBy=operation');
    expect(source).toContain("source: 'signal-dashboard-filter-selection'");
    expect(source).toContain("templateKey: 'metrics-graph'");
    expect(source).toContain("templateKey: 'metrics-table'");
    expect(source).toContain("templateKey: 'metrics-latency-p95'");
    expect(source).toContain("templateKey: 'metrics-request-rate'");
    expect(source).toContain("templateKey: 'metrics-error-rate'");
    expect(source).toContain("templateKey: 'metrics-apdex'");
    expect(source).toContain("templateKey: 'metrics-db-call-rate'");
    expect(source).toContain("templateKey: 'metrics-db-call-duration'");
    expect(source).toContain("templateKey: 'metrics-external-call-rate'");
    expect(source).toContain("templateKey: 'metrics-external-call-duration'");
    expect(source).toContain("templateKey: 'metrics-key-operations'");
    expect(source).toContain('template=service-apdex');
    expect(source).toContain('template=service-db-call-duration');
    expect(source).toContain('template=service-external-call-duration');
    expect(source).toContain('template=service-exceptions');
    expect(source).toContain('template=service-exception-messages');
    expect(source).toContain("templateKey: 'logs-list'");
    expect(source).toContain("templateKey: 'logs-errors'");
    expect(source).toContain("templateKey: 'traces-table'");
    expect(source).toContain("templateKey: 'traces-errors'");
    expect(source).toContain("templateKey: 'traces-exceptions'");
    expect(source).toContain("templateKey: 'traces-exception-messages'");
    expect(source).toContain("templateKey: 'alerts-firing'");
    expect(source).toContain("variableValue: 'billing'");
    expect(source).toContain("const persistedDashboard = await loadDashboard(page.context().request, dashboardKey)");
    expect(source).toContain("'Filter panel table: service.name=billing'");
    expect(source).toContain("'Filter panel latency p95: service.name=billing'");
    expect(source).toContain("'Filter panel request rate: service.name=billing'");
    expect(source).toContain("'Filter panel error rate: service.name=billing'");
    expect(source).toContain("'Filter panel apdex: service.name=billing'");
    expect(source).toContain("'Filter panel db calls rate: service.name=billing'");
    expect(source).toContain("'Filter panel db call duration: service.name=billing'");
    expect(source).toContain("'Filter panel external calls rate: service.name=billing'");
    expect(source).toContain("'Filter panel external call duration: service.name=billing'");
    expect(source).toContain("'Filter panel key operations: service.name=billing'");
    expect(source).toContain("'Filter panel logs: service.name=billing'");
    expect(source).toContain("'Filter panel log errors: service.name=billing'");
    expect(source).toContain("'Filter panel traces: service.name=billing'");
    expect(source).toContain("'Filter panel trace errors: service.name=billing'");
    expect(source).toContain("'Filter panel exceptions: service.name=billing'");
    expect(source).toContain("'Filter panel exception messages: service.name=billing'");
    expect(source).toContain("'Filter panel firing alerts: service.name=billing'");
    expect(source).toContain("expect.objectContaining({ x: 6, y: 4, w: 6, h: 4 })");
    expect(source).toContain("expect.objectContaining({ x: 6, y: 8, w: 6, h: 4 })");
    expect(source).toContain("for (const filterDraftKey of filterDraftKeys)");
    expect(source).toContain("dashboard-panel-draft/${encodeURIComponent(filterDraftKey.signal)}/${encodeURIComponent(filterDraftKey.draftKey)}");
    expect(source).toContain("createSignalDashboardPanelDraftFromRuntimeEvidence");
    expect(source).toContain("createSignalDashboardPanelDraftFromRuntimeBreakout");
    expect(source).toContain("persists a runtime evidence panel draft through the real panel-draft API");
    expect(source).toContain("persists runtime breakout panel drafts through the real panel-draft API");
    expect(source).toContain("const row: SignalDashboardRuntimeSyncTooltipRow");
    expect(source).toContain("titlePrefix: 'Evidence panel'");
    expect(source).toContain("draftKey === draftKey");
    expect(source).toContain("title: 'Evidence panel: http.server.duration'");
    expect(source).toContain("description: 'metrics-point · 120 · 1713200000000'");
    expect(source).toContain("source: 'signal-dashboard-runtime-evidence'");
    expect(source).toContain("evidenceValue: '120'");
    expect(source).toContain("source: 'signal-dashboard-runtime-breakout'");
    expect(source).toContain("breakoutAttribute: 'resource:service.version'");
    expect(source).toContain("breakoutAttributeValue: '1.2.3'");
    expect(source).toContain("titlePrefix = `Breakout panel ${proofKey}`");
    expect(source).toContain("groupBy=resource%3Aservice.version");
    expect(source).toContain("expect(savedLogDraft?.route).not.toContain('traceId=')");
    expect(source).toContain("expect(savedTraceDraft?.route).not.toContain('spanId=')");
    expect(source).toContain("dashboard-panel-draft/metrics/${encodeURIComponent(draftKey)}");
    expect(source).toContain("dashboard-panel-draft/${encodeURIComponent(draftKey.signal)}/${encodeURIComponent(draftKey.draftKey)}");
    expect(source).toContain("data-dashboard-composition-preview-edit-source-dashboard");
    expect(source).toContain('/dashboard?dashboard=${encodeURIComponent(dashboardKey)}&timeRange=last-1h');

    expect(source).not.toContain("page.route(");
    expect(source).not.toContain("installDashboardSourceEditMocks");
    expect(source).not.toContain("fulfillJson");
  });

  it('covers logs, traces, and metrics with route-specific edit actions', () => {
    const source = readFileSync(resolve(process.cwd(), 'scripts/dashboard-source-edit-live-browser-smoke.spec.ts'), 'utf8');

    expect(source).toContain("signal: 'logs'");
    expect(source).toContain("signal: 'traces'");
    expect(source).toContain("signal: 'metrics'");
    expect(source).toContain('data-log-manage-dashboard-panel-draft-action="update-current"');
    expect(source).toContain('data-trace-manage-dashboard-panel-draft-action="update-current"');
    expect(source).toContain('data-otlp-metrics-dashboard-panel-draft-action="update-current"');
    expect(source).toContain('search=latency');
    expect(source).toContain('operationName=GET+%2Fbilling');
    expect(source).toContain('query=process.runtime.jvm.memory.used');
  });
});
