import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

describe('three-signal browser smoke coverage', () => {
  it('keeps span-event marker selection and lucide event icons covered in the real browser smoke', () => {
    const source = readFileSync(resolve(process.cwd(), 'scripts/three-signal-workbench-browser-smoke.spec.ts'), 'utf8');

    expect(source).toContain("randomBytes(16).toString('hex')");
    expect(source).toContain('const BROWSER_SMOKE_TIMEOUT = 900000');
    expect(source).toContain('const LOG_ROW_VISIBLE_TIMEOUT = 60000');
    expect(source).not.toContain('TRACE_ID: THREE_SIGNAL_WORKBENCH_SMOKE_TRACE_ID');
    expect(source).toContain("['--ensure-entity']");
    expect(source).toContain("expect(message?.data?.tokenBoundary).toBe('bff-cookie')");
    expect(source).toContain('data-otlp-metrics-route="otlp-hertzbeat-ui-metrics-workbench"');
    expect(source).toContain('data-log-manage-route="otlp-hertzbeat-ui-log-workbench"');
    expect(source).toContain('logListApiUrl');
    expect(source).toContain('/api/logs/list?');
    expect(source).toContain('expectSeededLogListReady');
    expect(source).toContain('expectSeededLogRowVisible');
    expect(source).toContain('traceListApiUrl');
    expect(source).toContain('/api/traces/list?');
    expect(source).toContain('expectSeededTraceListReady');
    expect(source).toContain('expectSeededTraceDetailActionVisible');
    expect(source).toContain("await page.reload({ timeout: BROWSER_SMOKE_TIMEOUT, waitUntil: 'domcontentloaded' })");
    expect(source).toContain('expectLogRelatedTracePreviewFlow');
    expect(source).toContain('data-log-manage-detail-dialog-action="trace"');
    expect(source).toContain('data-log-related-trace-dialog="true"');
    expect(source).toContain('data-log-related-trace-open-workspace-action="true"');
    expect(source).toContain('expectLogDashboardDraftFlow');
    expect(source).toContain('data-log-manage-dashboard-panel-draft-action="add-current"');
    expect(source).toContain('data-log-manage-dashboard-panel-draft-status="saved"');
    expect(source).toContain("expect(draft.signal).toBe('logs')");
    expect(source).toContain("expect(draftPayload.source).toBe('logs-explorer')");
    expect(source).toContain("await page.unroute('**/api/signal/dashboard-panel-draft', routeHandler)");
    expect(source).toContain('data-trace-manage-route="otlp-hertzbeat-ui-trace-workbench"');
    expect(source).toContain('data-waterfall-event-marker-source="lucide"');
    expect(source).toContain('data-waterfall-event-marker-action="select-span-event"');
    expect(source).toContain(
      '[data-waterfall-event-marker="true"][data-waterfall-event-marker-action="select-span-event"]:not([data-waterfall-minimap-event-marker])'
    );
    expect(source).toContain('data-trace-manage-event-detail="span-event-detail"');
    expect(source).toContain("toHaveAttribute('data-trace-manage-event-detail-type', 'span-event')");
    expect(source).toContain('assertRelationEntityHref');
    expect(source).toContain('data-entity-detail-relationships-panel="upstream-downstream"');
    expect(source).toContain('smokeContext.hostEntityId');
    expect(source).toContain('smokeContext.k8sEntityId');
    expect(source).toContain('expectEntityResourceHandoffs');
    expect(source).toContain('expectTopologyResourceTarget');
    expect(source).toContain('topologyApiUrl');
    expect(source).toContain('/api/topology?');
    expect(source).toContain('expectTopologyApiReady');
    expect(source).toContain('expectTopologyRouteReady');
    expect(source).toContain("await page.reload({ timeout: BROWSER_SMOKE_TIMEOUT, waitUntil: 'domcontentloaded' })");
    expect(source).toContain('expectTraceRelatedMetricDashboardDraftFlow');
    expect(source).toContain('expectTraceRelatedLogsPreviewFlow');
    expect(source).toContain('data-trace-manage-drawer-related-logs="backend-related-logs"');
    expect(source).toContain('data-trace-manage-drawer-related-logs-owner');
    expect(source).toContain('data-trace-manage-drawer-related-logs-state');
    expect(source).toContain('data-trace-manage-drawer-related-logs-url');
    expect(source).toContain('data-trace-manage-drawer-related-log-action="open-logs"');
    expect(source).toContain('data-trace-manage-drawer-related-log-trace');
    expect(source).toContain('data-trace-manage-drawer-related-log-span');
    expect(source).toContain("expect(relatedLogsApiUrl.pathname).toBe('/logs/list')");
    expect(source).toContain("expect(relatedLogsApiUrl.searchParams.get('pageSize')).toBe('3')");
    expect(source).toContain("routeUrl('topologyHost', smokeContext)");
    expect(source).toContain("routeUrl('topologyK8s', smokeContext)");
    expect(source).toContain('data-topology-route="hertzbeat-entity-topology"');
    expect(source).toContain('data-topology-active-view-mode');
    expect(source).toContain('data-topology-edge-relationship-type="resource-ownership"');
    expect(source).toContain('data-hz-topology-detail-relation-type="resource-ownership"');
    expect(source).toContain('data-trace-manage-drawer-related-metric-query="container.cpu.usage"');
    expect(source).toContain('data-otlp-metrics-related-candidate-context="backend-related-metric-candidate"');
    expect(source).toContain('data-otlp-metrics-dashboard-panel-draft-action="add-current"');
    expect(source).toContain('data-otlp-metrics-dashboard-panel-draft-status="saved"');
    expect(source).toContain("savedUrl.searchParams.get('relatedMetricSource')");
    expect(source).toContain("savedUrl.searchParams.get('relatedMetricResourceMatch')");
    expect(source).toContain('host.name="checkout-node-a"');
    expect(source).toContain('k8s.namespace.name="payments" and k8s.pod.name="checkout-v1-78dfd" and container.name="checkout"');
    expect(source).not.toContain('spanEventDetail).toContainText');
  });
});
