import type { AlertDefine, PageResult } from '@/lib/types';
import { buildDefineListUrl } from './query-state';

type ApiGetter = <T>(url: string) => Promise<T>;
type ApiWriter = <T>(url: string, payload: unknown) => Promise<T>;

export async function loadDefineCenterData(apiGet: ApiGetter, search: string) {
  const [list, datasourceStatus] = await Promise.all([
    apiGet<PageResult<AlertDefine>>(buildDefineListUrl(search)),
    apiGet<{ code: number; data?: unknown; msg?: string }>('/alert/define/datasource/status')
  ]);
  return { list, datasourceStatus };
}

export type SettingDefinePageData = Awaited<ReturnType<typeof loadDefineCenterData>>;

export function buildPreviewUrl(selected: Pick<AlertDefine, 'datasource' | 'type' | 'expr'>) {
  const params = new URLSearchParams();
  if (selected.type) params.set('type', selected.type);
  if (selected.expr) params.set('expr', selected.expr);
  return `/alert/define/preview/${selected.datasource}?${params.toString()}`;
}

export function buildSkeletonDefine(): AlertDefine {
  return {
    id: 0,
    name: 'next-migrated-define',
    type: 'realtime_metric',
    datasource: 'promql',
    expr: 'up == 0',
    period: 300,
    times: 3,
    labels: { severity: 'warning' },
    annotations: { summary: 'generated by next migration' },
    enable: true,
    template: '',
    priority: 2
  };
}

export async function createSkeletonDefine(apiPost: ApiWriter) {
  return apiPost<string>('/alert/define', buildSkeletonDefine());
}

export async function saveDefine(apiPut: ApiWriter, selected: AlertDefine) {
  return apiPut<void>('/alert/define', selected);
}
