apiVersion: v1
kind: Service
metadata:
  name: "{{ include "hertzbeat.manager" . }}-cluster"
  labels:
    {{- include "hertzbeat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 1158
      targetPort: 1158
      protocol: TCP
      name: cluster
  selector:
    {{- include "hertzbeat.selectorLabels" . | nindent 4 }}
    component: manager
