apiVersion: v1
kind: Service
metadata:
  name: {{ include "hertzbeat.manager" . }}
  labels:
    {{- include "hertzbeat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - port: {{ .Values.manager.service.port }}
      targetPort: 1157
      protocol: TCP
      name: http
  selector:
    {{- include "hertzbeat.selectorLabels" . | nindent 4 }}
    component: manager
