-- ensure every sql can rerun without error

ALTER TABLE HZB_PARAM ADD COLUMN IF NOT EXISTS `value` VARCHAR(255);
UPDATE HZB_PARAM SET param_value = `value` WHERE `value` IS NOT NULL AND param_value IS NULL;
ALTER TABLE HZB_PARAM DROP COLUMN `value`;

ALTER TABLE HZB_TAG ADD COLUMN IF NOT EXISTS `value` VARCHAR(255);
UPDATE HZB_TAG SET tag_value = `value` WHERE `value` IS NOT NULL AND tag_value IS NULL;
ALTER TABLE HZB_TAG DROP COLUMN `value`;

ALTER TABLE HZB_STATUS_PAGE_HISTORY ADD COLUMN IF NOT EXISTS `unknown` VARCHAR(255);
UPDATE HZB_STATUS_PAGE_HISTORY SET unknowing = `unknown` WHERE `unknown` IS NOT NULL AND unknowing IS NULL;
ALTER TABLE HZB_STATUS_PAGE_HISTORY DROP COLUMN `unknown`;
