server {
  listen 80;
  server_name _;

  proxy_http_version 1.1;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location ^~ /_next/ {
    proxy_pass http://web-next:4200;
  }

  location ^~ /trace/ {
    proxy_pass http://web-next:4200;
  }

  location ^~ /log/ {
    proxy_pass http://web-next:4200;
  }

  location ^~ /monitors {
    proxy_pass http://web-next:4200;
  }

  location ^~ /ingestion/otlp {
    proxy_pass http://web-next:4200;
  }

  location ^~ /api/ {
    proxy_pass http://hertzbeat:1157;
  }

  location / {
    proxy_pass http://hertzbeat:1157;
  }
}
