-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements. See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0.
--
-- Static V206 schema baseline for provisioning an empty PostgreSQL target.
-- Future versioned migrations start at V207 or later.

    create table hzb_ai_conversation (
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        creator varchar(255),
        modifier varchar(255),
        title varchar(255),
        primary key (id)
    );

    create table hzb_ai_message (
        conversation_id bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        creator varchar(255),
        modifier varchar(255),
        role varchar(255),
        content oid not null,
        primary key (id)
    );

    create table hzb_alert_define (
        enable boolean not null,
        period integer,
        times integer,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        datasource varchar(100),
        name varchar(100) not null,
        expr varchar(2048),
        labels varchar(2048),
        template varchar(2048),
        annotations varchar(4096),
        creator varchar(255),
        modifier varchar(255),
        type varchar(255),
        primary key (id)
    );

    create table hzb_alert_define_monitor_bind (
        alert_define_id bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        monitor_id bigint,
        primary key (id)
    );

    create table hzb_alert_group (
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        common_labels varchar(2048),
        group_key varchar(2048),
        group_labels varchar(2048),
        alert_fingerprints TEXT,
        common_annotations TEXT,
        creator varchar(255),
        modifier varchar(255),
        status varchar(255),
        primary key (id),
        constraint unique_group_key unique (group_key)
    );

    create table hzb_alert_group_converge (
        enable boolean,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        group_interval bigint,
        group_wait bigint,
        id bigint generated by default as identity,
        repeat_interval bigint,
        name varchar(100) not null,
        group_labels varchar(1024),
        creator varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_alert_inhibit (
        enable boolean,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        name varchar(100) not null,
        equal_labels varchar(2048),
        source_labels varchar(2048),
        target_labels varchar(2048),
        creator varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_alert_silence (
        enable boolean not null,
        match_all boolean not null,
        times integer,
        type smallint not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        period_end timestamp(6) with time zone,
        period_start timestamp(6) with time zone,
        name varchar(100) not null,
        labels varchar(2048),
        creator varchar(255),
        days varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_alert_single (
        trigger_times integer,
        active_at bigint,
        end_at bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        start_at bigint,
        fingerprint varchar(2048),
        labels varchar(2048),
        annotations varchar(4096),
        content varchar(4096),
        creator varchar(255),
        modifier varchar(255),
        status varchar(255),
        primary key (id),
        constraint unique_fingerprint unique (fingerprint)
    );

    create table hzb_bulletin (
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        fields varchar(4096),
        monitor_ids varchar(4096),
        app varchar(255),
        creator varchar(255),
        modifier varchar(255),
        name varchar(255),
        primary key (id)
    );

    create table hzb_collector (
        status smallint not null check ((status>=0)),
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        creator varchar(255),
        ip varchar(255) not null,
        mode varchar(255),
        modifier varchar(255),
        name varchar(255) not null,
        version varchar(255),

        primary key (id),
        unique (name)
    );

    create table hzb_collector_monitor_bind (
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        monitor_id bigint,
        collector varchar(255),
        creator varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_config (
        gmt_create timestamp(6),
        gmt_update timestamp(6),

        content varchar(8192),
        creator varchar(255),
        modifier varchar(255),
        type varchar(255) not null,
        primary key (type)
    );

    create table hzb_define (
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        app varchar(255) not null,
        creator varchar(255),
        modifier varchar(255),
        content oid,
        primary key (app)
    );

    create table hzb_grafana_dashboard (
        enabled boolean not null,
        monitor_id bigint not null,
        version bigint,
        folder_uid varchar(255),
        slug varchar(255),
        status varchar(255),
        uid varchar(255),
        url varchar(255),
        primary key (monitor_id)
    );

    create table hzb_history (
        dou float(53),
        int32 integer,
        metric_type smallint,
        id bigint generated by default as identity,
        time bigint,
        str varchar(2048),
        app varchar(255),
        metric_labels varchar(5000),
        metric varchar(255),
        metrics varchar(255),
        instance varchar(255),
        primary key (id)
    );

    create table hzb_metrics_favorite (
        create_time timestamp(6),
        id bigint generated by default as identity,
        monitor_id bigint not null,
        creator varchar(255) not null,
        metrics_name varchar(255) not null,
        primary key (id),
        unique (creator, monitor_id, metrics_name)
    );

    create table hzb_monitor (
        intervals integer,
        status smallint not null check ((status<=4) and (status>=0)),
        type smallint not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint not null,
        job_id bigint,
        schedule_type varchar(20),
        app varchar(100),
        cron_expression varchar(100),
        instance varchar(100),
        name varchar(100),
        scrape varchar(100),
        annotations varchar(4096),
        labels varchar(4096),
        creator varchar(255),
        description varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_monitor_bind (
        biz_id bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        monitor_id bigint,
        creator varchar(255),
        key_str varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_notice_receiver (
        agent_id integer,
        lark_receive_type smallint,
        type smallint not null check ((type>=0)),
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        smn_ak varchar(22),
        smn_project_id varchar(32),
        smn_region varchar(32),
        smn_sk varchar(42),
        email varchar(100),
        name varchar(100) not null,
        phone varchar(100),
        access_token varchar(300),
        discord_bot_token varchar(300),
        discord_channel_id varchar(300),
        gotify_token varchar(300),
        hook_auth_token varchar(300),
        hook_auth_type varchar(300),
        server_chan_token varchar(300),
        slack_web_hook_url varchar(300),
        smn_topic_urn varchar(300),
        wechat_id varchar(300),
        hook_url varchar(1000),
        app_id varchar(255),
        app_secret varchar(255),
        chat_id varchar(255),
        corp_id varchar(255),
        creator varchar(255),
        modifier varchar(255),
        party_id varchar(255),
        tag_id varchar(255),
        tg_bot_token varchar(255),
        tg_message_thread_id varchar(255),
        tg_user_id varchar(255),
        user_id varchar(255),
        primary key (id)
    );

    create table hzb_notice_rule (
        enable boolean not null,
        filter_all boolean not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        period_end timestamp(6) with time zone,
        period_start timestamp(6) with time zone,
        template_id bigint,
        name varchar(100) not null,
        template_name varchar(100),
        labels varchar(2048),
        creator varchar(255),
        days varchar(255),
        modifier varchar(255),
        receiver_id varchar(255) not null,
        receiver_name varchar(255),
        primary key (id)
    );

    create table hzb_notice_template (
        preset boolean default false,
        type smallint not null check ((type>=0)),
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        name varchar(100) not null,
        creator varchar(255),
        modifier varchar(255),
        content oid not null,
        primary key (id)
    );

    create table hzb_param (
        type smallint not null check ((type>=0)),
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        monitor_id bigint,
        field varchar(100) not null,
        param_value varchar(8126),
        primary key (id),
        constraint uk_hzb_param_monitor_field unique (monitor_id, field)
    );

    create table hzb_param_define (
        hide boolean not null,
        param_limit smallint,
        required boolean not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        name varchar(2048),
        param_options varchar(2048),
        app varchar(255),
        creator varchar(255),
        default_value varchar(255),
        depend varchar(255),
        field varchar(255),
        key_alias varchar(255),
        modifier varchar(255),
        param_range varchar(255),
        placeholder varchar(255),
        type varchar(255),
        value_alias varchar(255),
        primary key (id)
    );

    create table hzb_plugin_item (
        id bigint generated by default as identity,
        metadata_id bigint,
        class_identifier varchar(255),
        type varchar(255) check ((type in ('POST_ALERT','POST_COLLECT'))),
        primary key (id)
    );

    create table hzb_plugin_metadata (
        enable_status boolean,
        param_count integer,
        gmt_create timestamp(6),
        id bigint generated by default as identity,
        creator varchar(255),
        jar_file_path varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table hzb_plugin_param (
        type smallint not null check ((type>=0)),
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        plugin_metadata_id bigint not null,
        field varchar(100) not null,
        param_value varchar(8126),
        primary key (id),
        constraint uk_hzb_plugin_param_metadata_field unique (plugin_metadata_id, field)
    );

    create table hzb_push_metrics (
        id bigint generated by default as identity,
        monitor_id bigint,
        time bigint,
        metrics varchar(255),
        primary key (id)
    );

    create table hzb_sop_schedule (
        id bigserial primary key,
        conversation_id bigint not null,
        sop_name varchar(64) not null,
        sop_params varchar(1024),
        cron_expression varchar(64) not null,
        enabled boolean default true,
        last_run_time timestamp,
        next_run_time timestamp,
        creator varchar(64),
        modifier varchar(64),
        gmt_create timestamp default current_timestamp,
        gmt_update timestamp default current_timestamp
    );

    comment on table hzb_sop_schedule is 'Scheduled SOP execution configurations';
    comment on column hzb_sop_schedule.conversation_id is 'Conversation ID to push results to';
    comment on column hzb_sop_schedule.sop_name is 'Name of the SOP skill to execute';
    comment on column hzb_sop_schedule.sop_params is 'SOP execution parameters in JSON format';
    comment on column hzb_sop_schedule.cron_expression is 'Cron expression for scheduling';
    comment on column hzb_sop_schedule.enabled is 'Whether the schedule is enabled';
    comment on column hzb_sop_schedule.last_run_time is 'Last execution time';
    comment on column hzb_sop_schedule.next_run_time is 'Next scheduled execution time';

    create table hzb_status_page_component (
        config_state smallint not null,
        method smallint not null,
        state smallint not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        org_id bigint,
        labels varchar(4096),
        creator varchar(255),
        description varchar(255),
        modifier varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table hzb_status_page_history (
        abnormal integer,
        normal integer,
        state smallint not null,
        unknowing integer,
        uptime float(53),
        component_id bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        timestamp bigint,
        creator varchar(255),
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_status_page_incident (
        state smallint not null,
        end_time bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        org_id bigint,
        start_time bigint,
        creator varchar(255),
        modifier varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table hzb_status_page_incident_component_bind (
        component_id bigint,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        incident_id bigint,
        primary key (id)
    );

    create table hzb_status_page_incident_content (
        state smallint not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        incident_id bigint,
        timestamp bigint,
        creator varchar(255),
        message TEXT not null,
        modifier varchar(255),
        primary key (id)
    );

    create table hzb_status_page_org (
        state smallint not null,
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        color varchar(255),
        creator varchar(255),
        description varchar(255) not null,
        feedback varchar(255),
        home varchar(255) not null,
        logo varchar(255) not null,
        modifier varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table hzb_tag (
        type smallint check ((type<=3) and (type>=0)),
        gmt_create timestamp(6),
        gmt_update timestamp(6),
        id bigint generated by default as identity,
        tag_value varchar(2048),
        creator varchar(255),
        description varchar(255),
        modifier varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create index idx_message_conversation_id
       on hzb_ai_message (conversation_id);

    create index idx_alert_define_id
       on hzb_alert_define_monitor_bind (alert_define_id);

    create index idx_monitor_id
       on hzb_alert_define_monitor_bind (monitor_id);

    create index idx_name
       on hzb_alert_group_converge (name);

    create index idx_collector_monitor_collector
       on hzb_collector_monitor_bind (collector);

    create index idx_collector_monitor_monitor_id
       on hzb_collector_monitor_bind (monitor_id);





    create index idx_hzb_history_instance
       on hzb_history (instance);

    create index idx_hzb_history_app
       on hzb_history (app);

    create index idx_hzb_history_metrics
       on hzb_history (metrics);

    create index idx_hzb_history_metric
       on hzb_history (metric);

    create index idx_hzb_monitor_app
       on hzb_monitor (app);

    create index idx_hzb_monitor_instance
       on hzb_monitor (instance);

    create index idx_hzb_monitor_name
       on hzb_monitor (name);

    create index index_monitor_bind
       on hzb_monitor_bind (biz_id);

    create index index_monitor_bin
       on hzb_monitor_bind (monitor_id);

    create index idx_hzb_param_monitor_id
       on hzb_param (monitor_id);

    create index idx_hzb_plugin_param_plugin_metadata_id
       on hzb_plugin_param (plugin_metadata_id);

    create index idx_push_metrics_monitor_id
       on hzb_push_metrics (monitor_id);

    create index idx_push_metrics_time
       on hzb_push_metrics (time);

    create index idx_schedule_conversation_id
       on hzb_sop_schedule (conversation_id);

    create index idx_schedule_enabled_next
       on hzb_sop_schedule (enabled, next_run_time);

    create index index_incident_component
       on hzb_status_page_incident_component_bind (incident_id);

    create index idx_incident_component_component_id
       on hzb_status_page_incident_component_bind (component_id);

    alter table if exists hzb_ai_message
       add constraint fk_hzb_ai_message_conversation
       foreign key (conversation_id)
       references hzb_ai_conversation;

    alter table if exists hzb_plugin_item
       add constraint fk_hzb_plugin_item_metadata
       foreign key (metadata_id)
       references hzb_plugin_metadata;

    alter table if exists hzb_status_page_incident_content
       add constraint fk_hzb_incident_content_incident
       foreign key (incident_id)
       references hzb_status_page_incident;

CREATE TABLE hzb_entity (
    id BIGINT PRIMARY KEY,
    entity_type VARCHAR(32) NOT NULL,
    name VARCHAR(128) NOT NULL,
    display_name VARCHAR(128),
    sub_type VARCHAR(128),
    namespace VARCHAR(128),
    environment VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    criticality VARCHAR(32),
    owner VARCHAR(128),
    additional_owners TEXT,
    runbook VARCHAR(512),
    lifecycle VARCHAR(64),
    tier VARCHAR(64),
    system_name VARCHAR(128),
    component_of TEXT,
    components TEXT,
    implemented_by TEXT,
    api_interface TEXT,
    inherit_from VARCHAR(255),
    languages TEXT,
    links TEXT,
    contacts TEXT,
    integrations TEXT,
    extensions TEXT,
    hertzbeat TEXT,
    source VARCHAR(32) NOT NULL,
    description VARCHAR(512),
    labels VARCHAR(4096),
    tags TEXT,
    workspace_id VARCHAR(64) NOT NULL DEFAULT 'default',
    creator VARCHAR(64),
    modifier VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gmt_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hzb_entity_type ON hzb_entity(entity_type);
CREATE INDEX idx_hzb_entity_status ON hzb_entity(status);
CREATE INDEX idx_hzb_entity_name ON hzb_entity(name);
CREATE INDEX idx_hzb_entity_owner ON hzb_entity(owner);
CREATE INDEX idx_hzb_entity_workspace ON hzb_entity(workspace_id);

CREATE TABLE hzb_entity_identity (
    id BIGSERIAL PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    identity_type VARCHAR(32) NOT NULL,
    identity_key VARCHAR(128) NOT NULL,
    identity_value VARCHAR(512) NOT NULL,
    normalized_value VARCHAR(512) NOT NULL,
    priority INT NOT NULL DEFAULT 40,
    primary_identity BOOLEAN NOT NULL DEFAULT FALSE,
    creator VARCHAR(64),
    modifier VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gmt_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_entity_identity ON hzb_entity_identity(entity_id, identity_key, normalized_value);
CREATE INDEX idx_hzb_entity_identity_lookup ON hzb_entity_identity(identity_key, normalized_value);
CREATE INDEX idx_hzb_entity_identity_entity ON hzb_entity_identity(entity_id);

CREATE TABLE hzb_entity_monitor_bind (
    id BIGSERIAL PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    monitor_id BIGINT NOT NULL,
    bind_type VARCHAR(32) NOT NULL,
    bind_source VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    score INT NOT NULL DEFAULT 100,
    match_context TEXT,
    creator VARCHAR(64),
    modifier VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gmt_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_entity_monitor_bind ON hzb_entity_monitor_bind(entity_id, monitor_id);
CREATE INDEX idx_hzb_entity_monitor_bind_entity ON hzb_entity_monitor_bind(entity_id);
CREATE INDEX idx_hzb_entity_monitor_bind_monitor ON hzb_entity_monitor_bind(monitor_id);

CREATE TABLE hzb_entity_relation (
    id BIGSERIAL PRIMARY KEY,
    source_entity_id BIGINT NOT NULL,
    target_entity_id BIGINT,
    target_ref VARCHAR(255),
    relation_type VARCHAR(32) NOT NULL,
    relation_source VARCHAR(32) NOT NULL,
    status VARCHAR(16) NOT NULL,
    score INT NOT NULL DEFAULT 100,
    description VARCHAR(255),
    attributes TEXT,
    creator VARCHAR(64),
    modifier VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gmt_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_entity_relation ON hzb_entity_relation(source_entity_id, target_entity_id, relation_type);
CREATE INDEX idx_hzb_entity_relation_source ON hzb_entity_relation(source_entity_id);
CREATE INDEX idx_hzb_entity_relation_target ON hzb_entity_relation(target_entity_id);
CREATE INDEX idx_hzb_entity_relation_target_ref ON hzb_entity_relation(target_ref);

CREATE TABLE hzb_entity_definition_activity (
    id BIGSERIAL PRIMARY KEY,
    entity_id BIGINT NOT NULL,
    workspace_id VARCHAR(64) NOT NULL DEFAULT 'default',
    activity_type VARCHAR(32) NOT NULL,
    format VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL,
    summary VARCHAR(128) NOT NULL,
    detail VARCHAR(255),
    creator VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_hzb_entity_definition_activity_entity
    ON hzb_entity_definition_activity(entity_id);

CREATE INDEX idx_hzb_entity_definition_activity_workspace_time
    ON hzb_entity_definition_activity(workspace_id, gmt_create);

CREATE INDEX idx_hzb_entity_definition_activity_time
    ON hzb_entity_definition_activity(gmt_create);

CREATE TABLE hzb_entity_governance_state (
    id BIGSERIAL PRIMARY KEY,
    state_scope VARCHAR(32) NOT NULL,
    state_kind VARCHAR(32) NOT NULL,
    workspace_id VARCHAR(64) NOT NULL DEFAULT 'default',
    state_key VARCHAR(128) NOT NULL,
    state_name VARCHAR(128),
    status VARCHAR(32),
    content TEXT,
    creator VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    gmt_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_entity_governance_state_scope_kind_workspace_key
    ON hzb_entity_governance_state(state_scope, state_kind, workspace_id, state_key);

CREATE INDEX idx_hzb_entity_governance_state_scope_kind
    ON hzb_entity_governance_state(state_scope, state_kind);

CREATE INDEX idx_hzb_entity_governance_state_scope_kind_workspace
    ON hzb_entity_governance_state(state_scope, state_kind, workspace_id);

CREATE INDEX idx_hzb_entity_governance_state_update
    ON hzb_entity_governance_state(gmt_update);

CREATE INDEX idx_hzb_entity_governance_state_creator
    ON hzb_entity_governance_state(creator);

CREATE TABLE hzb_auth_token (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    token_hash VARCHAR(128) NOT NULL,
    token_mask VARCHAR(64),
    token_scope VARCHAR(32) NOT NULL DEFAULT 'api-admin',
    workspace_id VARCHAR(64) NOT NULL DEFAULT 'default',
    status SMALLINT NOT NULL DEFAULT 0,
    creator VARCHAR(64),
    gmt_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expire_time TIMESTAMP NULL,
    last_used_time TIMESTAMP NULL,
    revoked_time TIMESTAMP NULL,
    revoked_by VARCHAR(64)
);

CREATE UNIQUE INDEX uk_hzb_auth_token_hash ON hzb_auth_token(token_hash);
CREATE INDEX idx_hzb_auth_token_creator ON hzb_auth_token(creator);
CREATE INDEX idx_hzb_auth_token_scope ON hzb_auth_token(token_scope);
CREATE INDEX idx_hzb_auth_token_workspace ON hzb_auth_token(workspace_id);
CREATE INDEX idx_hzb_auth_token_scope_workspace ON hzb_auth_token(token_scope, workspace_id);
CREATE INDEX idx_hzb_auth_token_status ON hzb_auth_token(status);
CREATE INDEX idx_hzb_auth_token_revoked_by ON hzb_auth_token(revoked_by);

CREATE TABLE hzb_signal_saved_view (
    id BIGSERIAL PRIMARY KEY,
    creator VARCHAR(255) NOT NULL,
    signal VARCHAR(32) NOT NULL,
    view_key VARCHAR(128) NOT NULL,
    label VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    route VARCHAR(2048) NOT NULL,
    query_snapshot TEXT,
    payload TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_signal_saved_view_signal_key
    ON hzb_signal_saved_view(signal, view_key);

CREATE INDEX idx_hzb_signal_saved_view_signal
    ON hzb_signal_saved_view(signal);

CREATE INDEX idx_hzb_signal_saved_view_update
    ON hzb_signal_saved_view(update_time);

CREATE TABLE hzb_signal_dashboard_panel_draft (
    id BIGSERIAL PRIMARY KEY,
    creator VARCHAR(255) NOT NULL,
    signal VARCHAR(32) NOT NULL,
    draft_key VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    visualization VARCHAR(32) NOT NULL,
    route VARCHAR(2048) NOT NULL,
    query_snapshot TEXT,
    payload TEXT,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_signal_dashboard_panel_draft_creator_signal_key
    ON hzb_signal_dashboard_panel_draft(creator, signal, draft_key);

CREATE INDEX idx_hzb_signal_dashboard_panel_draft_creator_signal
    ON hzb_signal_dashboard_panel_draft(creator, signal);

CREATE INDEX idx_hzb_signal_dashboard_panel_draft_update
    ON hzb_signal_dashboard_panel_draft(update_time);

CREATE TABLE hzb_signal_dashboard (
    id BIGSERIAL PRIMARY KEY,
    creator VARCHAR(255) NOT NULL,
    dashboard_key VARCHAR(128) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(512),
    tags VARCHAR(512),
    layout TEXT NOT NULL,
    widgets TEXT NOT NULL,
    variables TEXT,
    panel_map TEXT,
    version VARCHAR(32),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX uk_hzb_signal_dashboard_key
    ON hzb_signal_dashboard(dashboard_key);

CREATE INDEX idx_hzb_signal_dashboard_update
    ON hzb_signal_dashboard(update_time);

ALTER TABLE hzb_auth_token ADD COLUMN token_audience VARCHAR(32);
ALTER TABLE hzb_auth_token ADD COLUMN collector_id VARCHAR(128);
ALTER TABLE hzb_auth_token ADD COLUMN allowed_signals VARCHAR(64);
CREATE INDEX idx_hzb_auth_token_collector ON hzb_auth_token(collector_id);

ALTER TABLE hzb_collector ADD COLUMN runtime_config TEXT;

ALTER TABLE hzb_collector ADD COLUMN instrumentation_intake TEXT;

ALTER TABLE hzb_config ADD COLUMN config_revision VARCHAR(36);
UPDATE hzb_config SET config_revision = gen_random_uuid()::text WHERE config_revision IS NULL;
ALTER TABLE hzb_config ALTER COLUMN config_revision SET NOT NULL;

CREATE TABLE IF NOT EXISTS hzb_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    roles VARCHAR(128) NOT NULL,
    credential_version BIGINT NOT NULL,
    disabled BOOLEAN NOT NULL,
    bootstrap_slot SMALLINT,
    CONSTRAINT uk_hzb_account_username UNIQUE (username),
    CONSTRAINT uk_hzb_account_bootstrap UNIQUE (bootstrap_slot)
);
CREATE TABLE IF NOT EXISTS hzb_installation (
    id SMALLINT PRIMARY KEY,
    installation_fingerprint VARCHAR(64) NOT NULL UNIQUE,
    complete BOOLEAN NOT NULL
);
