#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

### add category
POST http://localhost:8080/api/category/upload/test
Content-Type: application/x-www-form-urlencoded

description=test

### modify category
POST http://localhost:8080/api/category/modify/1
Content-Type: application/x-www-form-urlencoded

name=Database monitoring&
description=数据库监控模版

### delete category
DELETE http://localhost:8080/api/category/delete/1

### get category by isDel
GET http://localhost:8080/api/category/all/0

### get category page by isDel
GET http://localhost:8080/api/category/page/isDel/0?page=0&size=10