spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hertzbeat2?useUnicode=true&characterEncoding=utf-8&useSSL=false
    platform: mysql
    hikari:
      max-lifetime: 120000
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.exmail.qq.com
    username: gongchao@tancloud.cn
    password: C7Roz9Qe3eGkiVM9
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    cache: true
    suffix: .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML

sureness:
  auths:
    - digest
    - basic
    - jwt

warehouse:
  store:
    td-engine:
      enabled: true
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      url: jdbc:TAOS-RS://127.0.0.1:6041/hertzbeat
      username: root
      password: taosdata