/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hertzbeat.ai.gateway.runtime;

import java.util.List;
import java.util.Objects;
import lombok.Builder;
import lombok.Getter;
import org.apache.hertzbeat.ai.gateway.contract.GatewayEnvelope;
import org.apache.hertzbeat.ai.gateway.contract.UserInput;
import org.apache.hertzbeat.common.entity.agent.AgentRun;
import org.apache.hertzbeat.common.entity.agent.AgentSession;

/**
 * Runtime request generated by Agent Gateway orchestration.
 */
@Getter
public class AgentRuntimeRequest {

    private final AgentRuntimeEntryType entryType;

    private final AgentApprovalHandling approvalHandling;

    private final GatewayEnvelope envelope;

    private final UserInput userInput;

    private final AgentSession session;

    private final AgentRun run;

    private final List<TranscriptMessage> chatHistory;

    @Builder
    private AgentRuntimeRequest(AgentRuntimeEntryType entryType, AgentApprovalHandling approvalHandling,
                                GatewayEnvelope envelope, UserInput userInput, AgentSession session, AgentRun run,
                                List<TranscriptMessage> chatHistory) {
        // Runtime requests are created after channel normalization; missing orchestration context is a programming error.
        this.entryType = Objects.requireNonNull(entryType, "Agent runtime entry type is required");
        this.approvalHandling = Objects.requireNonNull(approvalHandling,
                "Agent runtime approval handling is required");
        this.envelope = Objects.requireNonNull(envelope, "Agent runtime envelope is required");
        Objects.requireNonNull(envelope.getActor(), "Agent runtime envelope actor is required");
        this.userInput = Objects.requireNonNull(userInput, "Agent runtime user input is required");
        this.session = Objects.requireNonNull(session, "Agent runtime session is required");
        this.run = Objects.requireNonNull(run, "Agent runtime run is required");
        // Runtime and tool execution persist against saved session/run rows, so their identifiers must already exist.
        Objects.requireNonNull(session.getId(), "Agent runtime session id is required");
        if (!org.springframework.util.StringUtils.hasText(session.getSessionUid())) {
            throw new IllegalArgumentException("Agent runtime session uid is required");
        }
        Objects.requireNonNull(run.getId(), "Agent runtime run id is required");
        if (!org.springframework.util.StringUtils.hasText(run.getRunUid())) {
            throw new IllegalArgumentException("Agent runtime run uid is required");
        }
        Objects.requireNonNull(run.getSessionId(), "Agent runtime run session id is required");
        if (!session.getId().equals(run.getSessionId())) {
            throw new IllegalArgumentException("Agent runtime run must belong to the supplied session");
        }
        // Builder omission means the session has no replayable history; explicit entries must still be complete.
        this.chatHistory = chatHistory == null ? List.of() : List.copyOf(chatHistory);
    }
}
