/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.hertzbeat.manager.config;

import com.usthe.sureness.subject.PrincipalMap;
import com.usthe.sureness.subject.SubjectSum;
import com.usthe.sureness.util.JsonWebTokenUtil;
import com.usthe.sureness.util.SurenessContextHolder;
import io.jsonwebtoken.Claims;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.apache.hertzbeat.collector.dispatch.DispatchConstants;
import org.apache.hertzbeat.common.constants.NetworkConstants;
import org.apache.hertzbeat.common.observability.gateway.AuthTokenRequestContext;
import org.apache.hertzbeat.common.observability.gateway.AuthTokenScopes;
import org.apache.hertzbeat.common.observability.gateway.ObservabilityAccessTokenGateway;
import org.apache.hertzbeat.common.util.JsonUtil;
import org.apache.hertzbeat.manager.service.AccountService;
import org.apache.hertzbeat.manager.service.impl.AccountServiceImpl;
import org.jspecify.annotations.NonNull;
import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.apache.hertzbeat.common.observability.gateway.SelfTelemetryProperties;
import org.apache.hertzbeat.common.observability.gateway.TelemetrySource;
import org.apache.hertzbeat.common.observability.gateway.TelemetrySourceContext;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.AsyncHandlerInterceptor;

/**
 * Interceptor to validate that managed API tokens have not been revoked (deleted).
 * <p>
 * This interceptor runs AFTER the Sureness authentication filter to ensure:
 * 1. Only authenticated requests are checked (avoids unnecessary DB hits)
 * 2. lastUsedTime is only updated for successfully authenticated requests
 * <p>
 * Responsibility split:
 * - <b>Expiration</b>: handled by Sureness/JWT natively via the {@code exp} claim
 * - <b>Revocation</b>: handled here by checking the token's status in the database
 * - <b>Last used time</b>: updated here on each valid request (throttled)
 * <p>
 * Only tokens containing the "managed" claim (generated by the new token management system)
 * are validated against the database. Legacy tokens without this claim are allowed to pass
 * through for backward compatibility.
 * </p>
 */
@Component
@Slf4j
public class ApiTokenValidationFilter implements AsyncHandlerInterceptor {

    private static final String ROLES_CLAIM = "roles";
    private static final String TOKEN_VALIDATION_UNAVAILABLE = "Token validation unavailable";
    private static final String WORKSPACE_ACCESS_DENIED = "Workspace access denied";
    private static final String TOKEN_NOT_RESOLVED = "Token could not be resolved";
    private static final String TOKEN_PARAM = "token";

    private final AccountService accountService;
    private SelfTelemetryProperties selfTelemetry = new SelfTelemetryProperties();

    @Autowired
    public void setSelfTelemetryProperties(SelfTelemetryProperties properties) {
        this.selfTelemetry = properties;
    }

    public ApiTokenValidationFilter(AccountService accountService) {
        this.accountService = accountService;
    }

    @Override
    public boolean preHandle(@NonNull HttpServletRequest request, @NonNull HttpServletResponse response, @NonNull Object handler)
        throws IOException {
        TelemetrySourceContext.clear();
        AuthTokenRequestContext.clear();
        SubjectSum subject = SurenessContextHolder.getBindSubject();
        bindAuthenticatedWorkspace(subject);
        String authenticatedWorkspaceId = AuthTokenRequestContext.currentAuthenticatedWorkspaceId();
        if (subject == null || !isManagedToken(subject)) {
            if (!bindAuthorizedWorkspace(request, authenticatedWorkspaceId)) {
                return writeWorkspaceError(response);
            }
            return bindTelemetrySource(request, response, subject);
        }
        // Sureness reads a jwt from the Authorization header and from the token query parameter,
        // so every managed token the request carries is validated, and a managed subject whose
        // token cannot be found is rejected rather than let through unchecked
        List<String> managedTokens = resolveManagedTokens(request);
        if (managedTokens.isEmpty()) {
            return writeError(response, HttpStatus.UNAUTHORIZED, TOKEN_NOT_RESOLVED);
        }
        try {
            for (String token : managedTokens) {
                String rejectReason = checkManagedToken(
                        subject, token, resolveRequiredScope(request), authenticatedWorkspaceId);
                if (rejectReason != null) {
                    return writeError(response, HttpStatus.UNAUTHORIZED, rejectReason);
                }
            }
        } catch (RuntimeException e) {
            log.warn("Managed token validation failed", e);
            return writeError(response, HttpStatus.SERVICE_UNAVAILABLE, TOKEN_VALIDATION_UNAVAILABLE);
        }
        if (!bindAuthorizedWorkspace(request, authenticatedWorkspaceId)) {
            return writeWorkspaceError(response);
        }
        String rejectReason = bindManagedCollectorBoundary(request, subject);
        if (rejectReason != null) {
            return writeError(response, HttpStatus.UNAUTHORIZED, rejectReason);
        }
        managedTokens.forEach(this::touchTokenLastUsedTime);
        return bindTelemetrySource(request, response, subject);
    }

    @Override
    public void afterCompletion(@NonNull HttpServletRequest request, @NonNull HttpServletResponse response,
                                @NonNull Object handler, Exception ex) {
        AuthTokenRequestContext.clear();
        TelemetrySourceContext.clear();
    }

    @Override
    public void afterConcurrentHandlingStarted(@NonNull HttpServletRequest request,
                                               @NonNull HttpServletResponse response, @NonNull Object handler) {
        AuthTokenRequestContext.clear();
        TelemetrySourceContext.clear();
    }

    private boolean bindTelemetrySource(HttpServletRequest request, HttpServletResponse response, SubjectSum subject)
            throws IOException {
        String uri = request.getRequestURI();
        if (uri != null && !(uri.equals("/api/logs") || uri.startsWith("/api/logs/")
                || uri.equals("/api/traces") || uri.startsWith("/api/traces/")
                || uri.startsWith("/api/ingestion/otlp/") || uri.startsWith("/api/otlp/")
                || uri.equals("/api/warehouse/query") || uri.equals("/api/telemetry/sources"))) {
            return true;
        }
        TelemetrySource source;
        try {
            String[] values = request.getParameterValues("source");
            if (values != null && values.length != 1) {
                return writeError(response, HttpStatus.BAD_REQUEST, "Supply exactly one source");
            }
            source = TelemetrySource.parse(request.getParameter("source"));
        } catch (IllegalArgumentException invalid) {
            return writeError(response, HttpStatus.BAD_REQUEST, invalid.getMessage());
        }
        if (source == TelemetrySource.EXTERNAL) { return true; }
        if (uri == null || uri.startsWith("/api/otlp/") || uri.startsWith("/api/logs/otlp")) {
            return writeError(response, HttpStatus.BAD_REQUEST, "External ingestion cannot select self source");
        }
        if (!(uri.equals("/api/logs") || uri.startsWith("/api/logs/")
                || uri.equals("/api/traces") || uri.startsWith("/api/traces/")
                || uri.startsWith("/api/ingestion/otlp/metrics/"))) {
            return writeError(response, HttpStatus.BAD_REQUEST, "Self source is unsupported for this route");
        }
        if (subject == null || !extractClaimedRoles(subject).contains("admin")
                || resolveSubjectWorkspaceId(subject) == null
                || !java.util.Objects.equals(AuthTokenRequestContext.currentAuthenticatedWorkspaceId(),
                        selfTelemetry.getWorkspaceId())) {
            return writeError(response, HttpStatus.FORBIDDEN, "Self telemetry requires admin and an explicitly authorized workspace");
        }
        if (!selfTelemetry.isEnabled() || !selfTelemetry.isReady()) {
            return writeError(response, HttpStatus.SERVICE_UNAVAILABLE, "Self telemetry storage is not configured or ready");
        }
        if ("true".equalsIgnoreCase(request.getParameter("hideInternal"))) {
            return writeError(response, HttpStatus.BAD_REQUEST, "Disable hideInternal when selecting self telemetry");
        }
        TelemetrySourceContext.bind(new TelemetrySourceContext.Route(
                source, selfTelemetry.getDatabase(), selfTelemetry.getWorkspaceId()));
        return true;
    }

    private List<String> resolveManagedTokens(HttpServletRequest request) {
        Set<String> candidates = new LinkedHashSet<>(2);
        String authorization = request.getHeader(NetworkConstants.AUTHORIZATION);
        if (authorization != null && authorization.startsWith(DispatchConstants.BEARER)) {
            // mirror Sureness JwtSubjectJakartaServletCreator exactly, so the validated token is the one it authenticated
            candidates.add(authorization.replace(DispatchConstants.BEARER, "").trim());
        }
        String queryToken = request.getParameter(TOKEN_PARAM);
        if (queryToken != null) {
            candidates.add(queryToken.trim());
        }
        List<String> managedTokens = new ArrayList<>(candidates.size());
        for (String candidate : candidates) {
            if (!candidate.isEmpty() && isManagedJwt(candidate)) {
                managedTokens.add(candidate);
            }
        }
        return managedTokens;
    }

    private boolean isManagedJwt(String token) {
        try {
            Claims claims = JsonWebTokenUtil.parseJwt(token);
            return Boolean.TRUE.equals(claims.get(AccountServiceImpl.CLAIM_MANAGED, Boolean.class));
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Check if a managed token should be rejected.
     * <p>
     * Returns a rejection reason string if the token should be rejected, null if allowed.
     * Checks:
     * 1. Only managed tokens (with "managed" claim) are validated — legacy tokens pass through
     * 2. Token must exist and be active in the database (not deleted/revoked)
     * 3. Token owner must still exist, remain active, and still own the claimed roles
     * </p>
     */
    private String checkManagedToken(SubjectSum subject, String token, String requiredScope, String workspaceId) {
        String rejectReason = StringUtils.isBlank(workspaceId)
                ? accountService.checkTokenStatus(token, requiredScope)
                : accountService.checkTokenStatus(token, requiredScope, workspaceId);
        if (rejectReason != null) {
            return rejectReason;
        }
        rejectReason = accountService.checkManagedTokenAccess(
                getCurrentUserId(subject), extractClaimedRoles(subject), extractCredentialVersion(subject));
        if (rejectReason != null) {
            return rejectReason;
        }
        return null;
    }

    private void touchTokenLastUsedTime(String token) {
        try {
            accountService.touchTokenLastUsedTime(token);
        } catch (RuntimeException e) {
            log.debug("Failed to update token last used time");
        }
    }

    private boolean isManagedToken(SubjectSum subject) {
        PrincipalMap principalMap = subject.getPrincipalMap();
        if (principalMap == null) {
            return false;
        }
        Object managed = principalMap.getPrincipal(ObservabilityAccessTokenGateway.CLAIM_MANAGED);
        return managed instanceof Boolean ? (Boolean) managed : Boolean.parseBoolean(String.valueOf(managed));
    }

    @SuppressWarnings("unchecked")
    private List<String> extractClaimedRoles(SubjectSum subject) {
        Object roles = subject.getRoles();
        if (roles instanceof List<?>) {
            return (List<String>) roles;
        }
        PrincipalMap principalMap = subject.getPrincipalMap();
        if (principalMap == null) {
            return Collections.emptyList();
        }
        Object claimedRoles = principalMap.getPrincipal(ROLES_CLAIM);
        if (claimedRoles instanceof List<?>) {
            return (List<String>) claimedRoles;
        }
        return Collections.emptyList();
    }

    private String getCurrentUserId(SubjectSum subject) {
        Object principal = subject.getPrincipal();
        return principal == null ? null : String.valueOf(principal);
    }

    private Long extractCredentialVersion(SubjectSum subject) {
        PrincipalMap principalMap = subject.getPrincipalMap();
        if (principalMap == null) {
            return null;
        }
        Object claimedVersion = principalMap.getPrincipal(
                ObservabilityAccessTokenGateway.CLAIM_CREDENTIAL_VERSION);
        return claimedVersion instanceof Number number ? number.longValue() : null;
    }

    private String bindManagedCollectorBoundary(HttpServletRequest request, SubjectSum subject) {
        PrincipalMap principalMap = subject.getPrincipalMap();
        if (principalMap == null || !AuthTokenScopes.MANAGED_COLLECTOR_AUDIENCE.equals(
                principalMap.getPrincipal(AuthTokenScopes.CLAIM_TOKEN_AUDIENCE))) {
            return null;
        }
        Object collectorIdClaim = principalMap.getPrincipal(AuthTokenScopes.CLAIM_COLLECTOR_ID);
        String collectorId = collectorIdClaim == null
                ? null
                : StringUtils.trimToNull(String.valueOf(collectorIdClaim));
        if (collectorId == null) {
            return "Collector intake token has no Collector identity";
        }
        String signal = resolveOtlpSignal(request.getRequestURI());
        Object allowedSignals = principalMap.getPrincipal(AuthTokenScopes.CLAIM_ALLOWED_SIGNALS);
        if (signal == null || !(allowedSignals instanceof List<?> signals) || !signals.contains(signal)) {
            return "Collector intake token does not allow this signal";
        }
        AuthTokenRequestContext.bindCollectorId(collectorId);
        return null;
    }

    private String resolveOtlpSignal(String requestUri) {
        if (requestUri == null) {
            return null;
        }
        if (requestUri.startsWith("/api/logs/otlp") || requestUri.endsWith("/logs")) {
            return "logs";
        }
        if (requestUri.endsWith("/metrics")) {
            return "metrics";
        }
        if (requestUri.endsWith("/traces")) {
            return "traces";
        }
        return null;
    }

    private String resolveRequiredScope(HttpServletRequest request) {
        String requestUri = request.getRequestURI();
        if (requestUri != null
            && (requestUri.startsWith("/api/otlp/") || requestUri.startsWith("/api/logs/otlp"))) {
            return AuthTokenScopes.OTLP_INGEST;
        }
        String method = request.getMethod();
        if ("POST".equalsIgnoreCase(method) && "/api/logs/analysis/compare".equals(requestUri)) {
            return AuthTokenScopes.READONLY_QUERY;
        }
        if ("GET".equalsIgnoreCase(method) || "HEAD".equalsIgnoreCase(method) || "OPTIONS".equalsIgnoreCase(method)) {
            return AuthTokenScopes.READONLY_QUERY;
        }
        return AuthTokenScopes.API_ADMIN;
    }

    private boolean bindAuthorizedWorkspace(HttpServletRequest request, String authenticatedWorkspaceId) {
        String[] requestedWorkspaceIds = {
                request.getHeader(AuthTokenScopes.WORKSPACE_ID_HEADER),
                request.getParameter("workspaceId"),
                request.getParameter("workspace_id")
        };
        for (String requestedWorkspaceId : requestedWorkspaceIds) {
            String requested = StringUtils.trimToNull(requestedWorkspaceId);
            if (requested != null && (authenticatedWorkspaceId == null
                    || !authenticatedWorkspaceId.equals(AuthTokenScopes.normalizeWorkspaceId(requested)))) {
                return false;
            }
        }
        if (authenticatedWorkspaceId != null) {
            AuthTokenRequestContext.bindWorkspaceId(authenticatedWorkspaceId);
        }
        return true;
    }

    private void bindAuthenticatedWorkspace(SubjectSum subject) {
        if (subject == null) {
            return;
        }
        String workspaceId = resolveSubjectWorkspaceId(subject);
        AuthTokenRequestContext.bindAuthenticatedWorkspaceId(
                workspaceId == null ? AuthTokenScopes.DEFAULT_WORKSPACE_ID : workspaceId);
    }

    private String resolveSubjectWorkspaceId(SubjectSum subject) {
        if (subject == null || subject.getPrincipalMap() == null) {
            return null;
        }
        Object workspaceId = subject.getPrincipalMap().getPrincipal(AuthTokenScopes.CLAIM_WORKSPACE_ID);
        return workspaceId == null ? null : StringUtils.trimToNull(String.valueOf(workspaceId));
    }

    private boolean writeWorkspaceError(HttpServletResponse response) throws IOException {
        try {
            return writeError(response, HttpStatus.FORBIDDEN, WORKSPACE_ACCESS_DENIED);
        } finally {
            AuthTokenRequestContext.clear();
        }
    }

    private boolean writeError(HttpServletResponse response, HttpStatus status, String message) throws IOException {
        response.setStatus(status.value());
        response.setCharacterEncoding("UTF-8");
        response.setContentType("application/json");
        try (PrintWriter writer = response.getWriter()) {
            writer.write(JsonUtil.toJson(Map.of("code", status.value(), "msg", message)));
        } finally {
            // Rejected preHandle calls do not receive this interceptor's afterCompletion callback.
            AuthTokenRequestContext.clear();
            TelemetrySourceContext.clear();
        }
        return false;
    }
}
