### add category
POST http://localhost:8080/api/category/upload/test
Content-Type: application/x-www-form-urlencoded

description=test

### modify category
POST http://localhost:8080/api/category/modify/1
Content-Type: application/x-www-form-urlencoded

name=Database monitoring&
description=数据库监控模版

### delete category
DELETE http://localhost:8080/api/category/delete/1

### get category by isDel
GET http://localhost:8080/api/category/all/0

### get category page by isDel
GET http://localhost:8080/api/category/page/isDel/0?page=0&size=2