name: 'pdf-builder'
on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prince
        run: |
          sudo add-apt-repository multiverse
          sudo apt update && sudo apt install ttf-mscorefonts-installer
          sudo apt-get install language-pack-zh-han*
          sudo fc-cache -f -v
          LANG="zh_CN.UTF-8"
          curl https://www.princexml.com/download/prince-15.1-ubuntu20.04-amd64.tar.gz -O
          tar zxf prince-15.1-ubuntu20.04-amd64.tar.gz
          cd prince-15.1-ubuntu20.04-amd64
          yes "" | sudo ./install.sh
  
      - name: Build PDF
        run: npx docusaurus-prince-pdf -u https://hertzbeat.com/zh-cn/docs/ --output docs.pdf
  
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: result
          # The output filename can be specified with --output option
          path: docs.pdf
          if-no-files-found: error
  
