name: upload coverage reports to Codecov

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true
  workflow_dispatch:

jobs:
  upload-codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true