name: 'hertzbeat-doc-pdf-builder'
on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Prince
        run: |
          LANG="zh_CN.UTF-8"
          export LANG="zh_CN.UTF-8"
          curl https://www.princexml.com/download/prince-15.1-macos.zip -O
          tar zxf prince-15.1-macos.zip
          cd prince-15.1-macos
          yes "" | sudo ./install.sh
  
      - name: Build PDF
        run: npx docusaurus-prince-pdf -u https://hertzbeat.com/zh-cn/docs --output docs.pdf
  
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: result
          # The output filename can be specified with --output option
          path: docs.pdf
          if-no-files-found: error
  
